'use strict';
(()=>{
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const STORE='sana-gelen-yol-v1';
const fresh=()=>({version:1,current:0,unlocked:0,completed:[],memories:[],seen:[],states:{},minutes:0,volume:.4,assist:false});
let save=fresh(),storageOK=true;
try{const v=JSON.parse(localStorage.getItem(STORE));if(v&&v.version===1&&Array.isArray(v.completed)&&Array.isArray(v.memories)&&v.states){save={...fresh(),...v};save.current=Math.max(0,Math.min(14,Number(save.current)||0));save.unlocked=Math.max(0,Math.min(14,Number(save.unlocked)||0));}}catch{storageOK=false;}
let mode='home',priorMode='home',index=0,world,player,actor='sen',state,checkpoint=0,camera=0,W=1000,H=600,scale=1,clock=0,last=0,accum=0,near=null,deaths=0,flash=0,scene=null,sceneLine=0,sceneDone=null,sceneKey=null,sceneStart=0,ending=false,portraitAllowed=false;
const input={left:false,right:false,jump:false,jumpPressed:false};
let audioContext,gain,nextNote=0,noteIndex=0,music;
function store(){try{localStorage.setItem(STORE,JSON.stringify(save));}catch{if(storageOK)toast('Bu tarayıcı kayıt tutamıyor. İlerleme açık oturumda kalacak.');storageOK=false;}}
function persist(){if(world&&state){save.current=index;save.states[index]={checkpoint,phase:state.phase,gates:state.gates,lights:state.lights,tables:state.tables,actor};}store();}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function clearInput(){for(const k in input)input[k]=false;document.querySelectorAll('.held').forEach(e=>e.classList.remove('held'));}
function selectedTrack(){if(ending||(sceneKey==='14:outro'&&sceneLine>=9)||mode==='home')return null;return RoadMusic.chapters[sceneKey?Number(sceneKey.split(':')[0]):index];}
function syncMusic(gesture=false){if(!music)return;const track=selectedTrack();music.sync({track,playing:!document.hidden&&['play','scene'].includes(mode),volume:save.volume,duck:mode==='scene',gesture});$('musicUnlock').hidden=!music.blocked||mode==='modal'||mode==='home'||document.hidden||!save.volume;}
function soundStart(){try{if(!audioContext){audioContext=new(window.AudioContext||window.webkitAudioContext)();gain=audioContext.createGain();gain.connect(audioContext.destination);}gain.gain.value=save.volume;if(!document.hidden)audioContext.resume().catch(()=>{});}catch{}if(!music)music=RoadMusic.create({element:$('soundtrack'),context:audioContext,onBlocked:blocked=>{$('musicUnlock').hidden=!blocked||mode==='modal'||!save.volume;},onError:()=>toast('Müzik yüklenemedi. Yoluna devam edebilirsin.')});syncMusic(true);}
function tone(freq,duration=.8,vol=.1,type='sine'){if(!audioContext||audioContext.state!=='running'||!gain)return;const t=audioContext.currentTime,o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(gain);o.start();o.stop(t+duration+.02);}
function ambience(){syncMusic();if(selectedTrack()&&!music?.failed)return;if(document.hidden||mode==='paused'||mode==='modal'||!audioContext)return;if(clock>nextNote){nextNote=clock+(ending?3.5:1.7);if(!ending){const seq=[220,329.63,293.66,0,261.63,329.63,196,0];const f=seq[noteIndex++%8];if(f)tone(f*(index>11?.75:1),2.4,.045);}else tone(1300+Math.sin(clock)*130,.09,.007);}}
function resize(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';H=600;W=innerWidth/innerHeight*H;scale=canvas.height/H;orientation();}
function orientation(){const show=innerHeight>innerWidth&&!portraitAllowed&&mode!=='home'&&mode!=='modal';$('rotate').hidden=!show;if(show&&mode==='play')pause();}
function hud(){const d=LEVELS[index];$('worldLabel').textContent=WORLDS[d.w].short+' / '+String(index+1).padStart(2,'0')+' — 15';$('levelLabel').textContent=d.title;$('actorLabel').textContent=actor==='damla'?'DAMLA':'SEN';$('memoryCount').textContent='✧ '+save.memories.length;$('routeCount').textContent=Object.keys(state?.lights||{}).length+'/3 İZ';$('objective').textContent=d.goal;}
function startLevel(i,resume=false){index=i;ending=false;actor=LEVELS[i].actor;world=RoadEngine.makeLevel(i,LEVELS[i]);const old=resume?save.states[i]:null;state={time:0,phase:old?.phase||0,gates:{...(old?.gates||{})},lights:{...(old?.lights||{})},tables:{...(old?.tables||{})},assist:save.assist};checkpoint=old?.checkpoint||0;actor=old?.actor||actor;const cp=world.checkpoints[checkpoint]||world.checkpoints[0];player=RoadEngine.createPlayer(cp.x,cp.y);camera=Math.max(0,player.x-W*.32);deaths=0;mode='play';priorMode='play';$('modal').hidden=true;$('home').hidden=true;$('hud').hidden=false;$('controls').hidden=false;$('objective').hidden=false;clearInput();hud();persist();soundStart();orientation();if(!resume||!save.seen.includes(i+':intro'))showScene(LEVELS[i].intro,()=>{orientation();},i+':intro');}
function showScene(lines,done=()=>{},key=null){clearInput();scene=lines;sceneLine=0;sceneDone=done;sceneKey=key;sceneStart=clock;mode='scene';soundStart();$('dialogue').hidden=false;$('controls').hidden=true;showLine();}
function showLine(){const l=scene[sceneLine];const who=l[0]==='SEN'?'sen':l[0]==='DAMLA'?'damla':null;$('portrait').hidden=!who;$('dialogue').classList.toggle('has-portrait',!!who);if(who)RoadCharacters.portrait($('portrait'),who);syncMusic(true);$('speaker').textContent=l[0];$('line').textContent=l[1];$('lineCount').textContent=String(sceneLine+1).padStart(2,'0')+' / '+String(scene.length).padStart(2,'0');$('nextLine').textContent=sceneLine===scene.length-1?'Yola devam →':'Devam →';tone(440,.1,.008);}
function finishScene(){if(sceneKey&&!save.seen.includes(sceneKey)){save.seen.push(sceneKey);store();}const fn=sceneDone;scene=null;sceneKey=null;$('dialogue').hidden=true;mode='play';$('controls').hidden=false;clearInput();fn();}
function nextLine(){if(!scene)return;if(sceneKey==='0:intro'&&sceneLine===4)flash=.9;if(++sceneLine>=scene.length)finishScene();else showLine();}
function openModal(title,body,returnMode=mode){priorMode=returnMode;mode='modal';clearInput();$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').hidden=false;$('controls').hidden=true;syncMusic();}
function closeModal(){ $('modal').hidden=true;mode=priorMode;clearInput();$('controls').hidden=mode!=='play';soundStart();orientation();}
function menuButton(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;b.className=primary?'primary':'secondary';b.onclick=fn;return b;}
function addButtons(actions){const row=document.createElement('div');row.className='menu-buttons';for(const [text,fn,primary]of actions)row.append(menuButton(text,fn,primary));$('modalBody').append(row);}
function pause(){if(!['play','scene','ending'].includes(mode))return;const ret=mode;persist();openModal('Yol burada bekler.',`<p>İlerlemen bu cihazda otomatik kaydediliyor. Acele etmene gerek yok.</p><div class="settings"><label>Ses <input id="volume" type="range" min="0" max="1" step=".05" value="${save.volume}" aria-label="Ses seviyesi"></label><label><input id="assist" type="checkbox" ${save.assist?'checked':''}> Kolaylaştırılmış zıplama</label></div>`,ret);$('volume').oninput=e=>{save.volume=+e.target.value;if(gain)gain.gain.value=save.volume;syncMusic(true);store();};$('assist').onchange=e=>{save.assist=e.target.checked;if(state)state.assist=save.assist;store();};addButtons([['Devam et',closeModal,true],['Bölümü baştan oyna',()=>startLevel(index)],['Kontrol noktasına dön',()=>{closeModal();if(mode==='scene')finishScene();respawn(false);}],['Bölümler ve anılar',()=>chapterMenu(ret)],['Ana menü',home]]);}
function home(){persist();mode='home';scene=null;ending=false;$('dialogue').hidden=true;$('modal').hidden=true;$('hud').hidden=true;$('objective').hidden=true;$('controls').hidden=true;$('home').hidden=false;$('rotate').hidden=true;$('continue').hidden=!Object.keys(save.states).length;$('start').hidden=Object.keys(save.states).length>0;clearInput();syncMusic();}
function about(){openModal('Bir insana çıkan yollar.',`<p>Damla ve senin hikâyenden beslenen, beş dünyada geçen bir yolculuk. Karakterler gönderdiğiniz fotoğraflardaki saç, yüz ve kıyafet ayrıntıları esas alınarak yeniden çizildi. Gerçek olarak belirtilmeyen konuşmalar, mekân ayrıntıları ve final repliği bu oyun için yazılmış kurgu.</p><p>Bu ilk oynanabilir sürüm 15 bölümün tamamını içerir. 1,5–2 saatlik hedef süre henüz oyuncu testleriyle doğrulanmadı.</p><p>“Şamdanları Donanınca” bir ses anısı olarak anılır; şarkının kaydı, sözleri veya melodisi kullanılmaz. Bazı bölümlerde gönderdiğiniz üç kayıt çalar: Yann Tiersen — Naval; Jóhann Jóhannsson — The Rocket Builder; Max Richter — On the Nature of Daylight. Diğer bölümlerde kısa özgün tema duyulur. Seçilmeyen İsmet Özel şiirinden alıntı yoktur.</p><p class="note">Telefonda yatay tut: solda yönler, sağda zıplama. Daha yüksek atlamak için zıplamayı basılı tut. Altın işaretlere yaklaşınca ✧ görünür. Bilgisayarda A/D veya ←/→, Boşluk ile zıpla, E ile etkileş. Esc duraklatır.</p><p>Kayıt aynı cihaz ve tarayıcıda saklanır. Verileri silmek ilerlemeyi silebilir. Düşmek hikâyeyi değiştirmez; son kontrol noktasından devam edersin.</p>`);}
function chapterMenu(ret=mode){openModal('Geçtiğin yollar.',`<p>Tamamladığın bölümleri yeniden oyna; gördüğün sahneleri tekrar izle.</p>`,ret);for(let w=0;w<5;w++){const title=document.createElement('div');title.className='world-title';title.textContent=WORLDS[w].name.toLocaleUpperCase('tr');$('modalBody').append(title);const grid=document.createElement('div');grid.className='chapter-grid';for(let n=w*3;n<w*3+3;n++){const b=menuButton('',()=>{if(save.completed.includes(n))startLevel(n);else if(save.states[n])startLevel(n,true);else startLevel(n);});b.className='chapter-tile';b.disabled=n>save.unlocked;b.innerHTML=`<span>${String(n+1).padStart(2,'0')} ${save.completed.includes(n)?'✓ TAMAMLANDI':n>save.unlocked?'· KİLİTLİ':''}</span><strong>${LEVELS[n].title}</strong>`;grid.append(b);}$('modalBody').append(grid);}addButtons([['Anı defteri',()=>memoryMenu(ret)],['İzlenen sahneler',()=>sceneMenu(ret)]]);}
function memoryMenu(ret){openModal('Yanına aldıkların.',`<p>${save.memories.length} / 45 anı parçası. Anıları toplamak finali değiştirmez.</p>`,ret);for(let i=0;i<15;i++)if(save.memories.some(v=>v.startsWith(i+':'))){const e=document.createElement('div');e.className='memory-entry';e.innerHTML='<strong>'+LEVELS[i].memory[0]+'</strong><p>'+LEVELS[i].memory[1]+'</p>';$('modalBody').append(e);}if(!save.memories.length)$('modalBody').innerHTML+='<p>Işıktan yapılmış küçük yıldızlar, ana yolun üstündeki gizli platformlarda seni bekler.</p>';}
function sceneMenu(ret){const original={scene,sceneLine,sceneDone,sceneKey};openModal('Hatırlanan sahneler.','<p>Gördüğün açılış ve kapanış sahneleri burada kalır.</p>',ret);for(const key of save.seen){const [n,part]=key.split(':');if(!LEVELS[n])continue;const b=menuButton(`${+n+1}. ${LEVELS[n].title} · ${part==='intro'?'Açılış':'Kapanış'}`,()=>{$('modal').hidden=true;showScene(LEVELS[n][part],()=>{scene=original.scene;sceneLine=original.sceneLine;sceneDone=original.sceneDone;sceneKey=original.sceneKey;if(scene){$('dialogue').hidden=false;showLine();}mode=ret;sceneMenu(ret);});});b.style.margin='5px';$('modalBody').append(b);}}
function respawn(count=true){const cp=world.checkpoints[checkpoint];player=RoadEngine.createPlayer(cp.x,cp.y);RoadEngine.resetPlatforms(world);clearInput();flash=.4;if(count){deaths++;tone(110,.25,.08);toast('Yol bitmedi. Son ışığından devam.');if(deaths===4&&!save.assist){openModal('Biraz daha kolay olsun mu?','<p>Bu engelde birkaç kez düştün. Zıplama yardımını açabilirsin; hikâye ve final değişmez.</p>','play');addButtons([['Yardımı aç',()=>{save.assist=true;state.assist=true;store();closeModal();},true],['Kendim deneyeceğim',closeModal]]);}}camera=Math.max(0,player.x-W*.32);}
function objectAvailable(o){if(o.type==='memory')return !save.memories.includes(index+':'+o.id);if(o.type==='light'||o.type==='table')return !state.lights[o.n];if(o.type==='lever')return !state.gates[o.n];if(o.type==='clock')return ['phase','compare','mixed'].includes(LEVELS[index].mechanic);return true;}
function interact(){if(mode!=='play'||!near)return;const o=near;
 if(o.type==='memory'){save.memories.push(index+':'+o.id);store();hud();tone(659,1,.09);showScene([['BİR ANI · '+LEVELS[index].memory[0],LEVELS[index].memory[1]]]);return;}
 if(o.type==='clock'){state.phase=1-state.phase;persist();flash=.2;toast(state.phase?'Öteki akşam · mor yollar katı':'İlk akşam · altın yollar katı');tone(state.phase?392:330,.5,.06);return;}
 if(o.type==='lever'){state.gates[o.n]=true;persist();tone(146,.8,.08);toast('Döngü kapandı. Karşı çıkış açıldı.');return;}
 if(o.type==='table'){tablePuzzle(o);return;}
 if(o.type==='light'){activate(o);return;}
 if(o.type==='exit'){
  if(Object.keys(state.lights).length<3){toast('Üç işaretin hepsi gerekli. Geride kalan sıcak ışıklara dön.');return;}
  if(index===14){openModal('Son bağlantı.',`<p>Geçit açık kalırsa Damla aynı anılara dönecek. Kapatırsan onun çıkışı açılacak ve aranızdaki son yol kesilecek.</p><p>İkiniz de yaşayacak, ikiniz de devam edebileceksiniz. Yollarınız birleşmeyecek.</p>`,'play');addButtons([['Geçidi kapat',()=>{$('modal').hidden=true;complete();},true],['Biraz daha burada kal',closeModal]]);}else complete();
 }
}
function activate(o){state.lights[o.n]=true;if(LEVELS[index].mechanic==='relay'&&o.n===0)actor='damla';persist();hud();tone(523,.8,.1);showScene([LEVELS[index].signs[o.n]],()=>{if(actor==='damla'&&index===13)toast('Şimdi Damla’nın yolundasın.');});}
function tablePuzzle(o){let pair=state.tables[o.n]||[0,0];const names=['Barbeküs','Kremantar','Köri'];openModal('Her zamankinden.',`<p>Damla’nın tabağı solda, seninki sağda. Siparişleri hatırla.</p><div class="menu-buttons"><button class="secondary" id="dishLeft"></button><button class="secondary" id="dishRight"></button></div><p id="tableHint"></p>`,'play');const draw=()=>{$('dishLeft').textContent='Damla: '+names[pair[0]];$('dishRight').textContent='Sen: '+names[pair[1]];$('tableHint').textContent=index===10?(state.phase===0?'Masanın üzerinde yıldızlı peçete var.':'Mavi atkılı akşam. Yıldızlı peçeteyi öteki zamanda ara.'):'Menüye bakıp yine aynı şeyi seçmek.';};$('dishLeft').onclick=()=>{pair[0]=(pair[0]+1)%3;draw();};$('dishRight').onclick=()=>{pair[1]=(pair[1]+1)%3;draw();};draw();addButtons([['Masayı hatırla',()=>{state.tables[o.n]=pair;persist();if(pair[0]===1&&pair[1]===0&&(index!==10||state.phase===0)){$('modal').hidden=true;activate(o);}else{tone(165,.2,.05);$('tableHint').textContent=index===10&&state.phase!==0?'Önce yıldızlı peçetenin olduğu akşama dön.':'Bir şey eksik. Damla Kremantar, sen Barbeküs seviyordun.';}},true],['Yola dön',closeModal]]);}
function complete(){const d=LEVELS[index];if(!save.completed.includes(index))save.completed.push(index);save.unlocked=Math.max(save.unlocked,Math.min(index+1,14));persist();showScene(d.outro,()=>{if(index===14){ending=true;mode='ending';$('hud').hidden=true;$('objective').hidden=true;$('controls').hidden=true;setTimeout(()=>{if(mode==='ending'){openModal('Sana Gelen Yol',`<p>Damla yoluna devam ediyor. Sen de.</p><p>Yanında kalan ${save.memories.length} anı parçası var. Yolun burada bitti; yaşadıkların silinmedi.</p><p class="note">Final konuşması, sizin gerçek konuşma biçiminize göre daha sonra değiştirilebilecek özgün bir kurgu.</p>`,'ending');addButtons([['Biraz daha otur',closeModal,true],['Anı defteri',()=>memoryMenu('ending')],['Ana menü',home]]);}},7000);}else{openModal('Bir sonraki iz.',`<p>${index+1}. bölüm tamamlandı.</p><p>Sıradaki: <strong>${LEVELS[index+1].title}</strong></p>`,'play');addButtons([['Yola devam',()=>startLevel(index+1),true],['Bölümler',()=>chapterMenu('play')],['Ana menü',home]]);}},index+':outro');}
function update(dt){if(mode!=='play')return;state.time+=dt;state.jumped=false;const dead=RoadEngine.step(world,player,input,state,dt);input.jumpPressed=false;if(state.jumped)tone(350,.13,.024);if(dead){respawn();return;}if(player.ground!==null){for(let n=0;n<world.checkpoints.length;n++){const cp=world.checkpoints[n];if(n>checkpoint&&player.x>=cp.x-40&&player.x<cp.x+300){checkpoint=n;deaths=0;persist();toast('Kontrol noktası · Kaydedildi');tone(440,.4,.05);}}}near=null;let distance=95;for(const o of world.objects){if(!objectAvailable(o))continue;const dist=Math.hypot(player.x+13-o.x,(player.y+player.h)-(o.y));if(dist<distance){near=o;distance=dist;}}$('interact').hidden=!near;if(near){const labels={memory:'Anıyı al',light:actor==='damla'?(index===8&&near.n===2?'Notu bırak':'Işığı yak'):'İzi oku',clock:'Zamanı değiştir',lever:'Kapıyı kapat',table:'Masaya bak',exit:index===14?'Son geçit':'Yola devam'};$('interactLabel').textContent=labels[near.type];}const target=Math.max(0,Math.min(world.width-W,player.x-W*.32));camera+=(target-camera)*Math.min(1,dt*5);$('progressFill').style.width=Math.max(0,Math.min(100,player.x/world.width*100))+'%';save.minutes+=dt/60;}
// Painted vector scenery and photo-referenced characters; music loads per chapter.
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function path(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
function line(x,y,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function glow(x,y,r,alpha=.22){const g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,`rgba(255,217,151,${alpha})`);g.addColorStop(1,'rgba(255,198,110,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function text(str,x,y,size=12,color='#e9c995',align='center'){ctx.fillStyle=color;ctx.textAlign=align;ctx.font=size+'px system-ui';ctx.fillText(str,x,y);}
function tree(x,y,s,tint,seed=0){ctx.save();ctx.translate(x,y);ctx.scale(s,s);path([[-12,0],[-7,-149],[-42,-217],[-25,-215],[2,-163],[28,-237],[36,-230],[9,-119],[15,0]],'#243b43');for(let j=0;j<37;j++){const a=j*2.399+seed,rx=Math.sin(j*3.7+seed)*68,ry=-205+Math.cos(j*1.7+seed)*50;ellipse(rx,ry,40+Math.sin(a)*12,22+Math.cos(a)*9,tint);if(j%4===0)ellipse(rx-3,ry-4,30,12,'#dfbc8112');}ctx.restore();}
function bench(x,y,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);line(-53,-12,-50,16,'#182832',5);line(54,-12,51,16,'#182832',5);for(let n=0;n<4;n++){ctx.fillStyle=n===3?'#b08b68':'#927255';ctx.fillRect(-66,-45+n*11,133,7);}ctx.fillStyle='#c6a07b';ctx.fillRect(-73,-5,147,7);line(-57,-51,-57,-1,'#243337',4);line(60,-51,60,-1,'#243337',4);ctx.restore();}
function lamp(x,y,lit=true,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);if(lit)glow(0,-115,85,.2);line(0,0,0,-116,'#27333a',5);line(-17,-128,17,-128,'#27333a',5);path([[-20,-129],[0,-142],[20,-129]],'#27333a');ctx.fillStyle=lit?'#ffe2a3':'#697b87';ctx.fillRect(-11,-123,22,24);line(-12,-126,-9,-97,'#29343a',3);line(12,-126,9,-97,'#29343a',3);ctx.fillStyle='#29343a';ctx.fillRect(-13,-100,26,4);ctx.restore();}
function character(x,y,who='sen',facing=1,moving=false,seated=false,alpha=1){RoadCharacters.draw(ctx,{x,y,who,facing,moving,seated,alpha,time:clock,steps:player?.steps||0});}
function backdrop(def,cam=0,isHome=false){const pal=WORLDS[def.w],phase=state?.phase||0;const g=ctx.createLinearGradient(0,0,0,530);g.addColorStop(0,pal.sky[0]);g.addColorStop(.62,pal.sky[1]);g.addColorStop(1,pal.sky[2]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(phase&&['phase','compare','mixed'].includes(def.mechanic)){ctx.fillStyle='#30256355';ctx.fillRect(0,0,W,H);}const sunX=W*.73-cam*.015;glow(sunX,214,210,.13);ellipse(sunX,214,33,33,'#f5cdaa55');for(let j=0;j<12;j++){const xx=((j*239.13-cam*.04)%(W+300)+W+300)%(W+300)-150;ellipse(xx,95+(j%4)*35,110,11,'#ead5c70a');}
 for(let layer=0;layer<3;layer++){const pts=[[0,600]];for(let x=-80;x<W+100;x+=35)pts.push([x,315+layer*53+Math.sin((x+cam*.1+layer*201)*.007)*28+Math.cos(x*.013+layer)*11]);pts.push([W+100,600]);path(pts,['#60758255','#425c6888','#2e4858'][layer]);}
 if(['city','end'].includes(pal.type)){for(let n=-1;n<14;n++){const x=n*123-(cam*.2%123),h=57+Math.sin(n*8.2)*30;ctx.fillStyle='#334759';ctx.fillRect(x,335-h,91,h+60);path([[x-4,335-h],[x+44,315-h],[x+96,335-h]],'#394c5d');for(let j=0;j<4;j++)for(let k=0;k<3;k++)ctx.fillStyle=(n+j+k)%4===0?'#d5ba7b88':'#70808a33',ctx.fillRect(x+12+j*20,345-h+k*21,8,12);}line(0,300,W,310,'#9da7a344',2);}
 if(pal.type==='cafe'){ctx.fillStyle='#3b353a99';ctx.fillRect(0,80,W,360);for(let n=-1;n<10;n++){const x=n*220-(cam*.2%220);ctx.fillStyle='#d1a47a55';ctx.fillRect(x+30,136,145,216);for(let j=0;j<3;j++)line(x+40+j*50,138,x+40+j*50,350,'#433c40',6);line(x+30,240,x+175,240,'#433c40',5);line(x+100,80,x+100,137,'#b3a38d',2);glow(x+100,168,78,.22);path([[x+78,156],[x+88,140],[x+112,140],[x+122,156]],'#e2b282');}text('TAVUK DÜNYASI',W*.62,108,13,'#f0c697');}
 for(let n=-1;n<9;n++){const x=n*260-(cam*.28%260);tree(x+90,444,.64,pal.leaf+'b0',n*4);}
 if(isHome){path([[0,469],[W*.42,451],[W*.68,430],[W,442],[W,600],[0,600]],'#314449');path([[0,531],[W*.37,481],[W*.75,445],[W,454],[W,483],[W*.7,473],[W*.35,520],[0,591]],'#b398773b');const bx=W*.73;tree(W*.97,480,1.9,'#314d4d',3);tree(W*.16,463,1.45,'#354e50',7);lamp(bx+115,440,true,1.16);bench(bx,445,1.1);character(bx-23,441,'sen',1,false,true);if(!ending&&!(sceneKey=== '14:outro'&&sceneLine>=9))character(bx+30,441,'damla',-1,false,true);for(let n=0;n<52;n++){const x=(n*73.1)%W,y=460+(n*39.7)%140;line(x,y,x+Math.sin(n)*7,y-9,'#88917538',1);} }
 if(pal.type==='rain'){ctx.strokeStyle='#b8d2d333';ctx.lineWidth=1;for(let n=0;n<80;n++){const x=((n*67+clock*105)% (W+30))-15,y=(n*47+clock*340)%600;line(x,y,x-6,y+17,'#b8d2d330');}}else{for(let n=0;n<23;n++){const x=(n*97.5+Math.sin(clock*.4+n)*16-cam*.12)%(W+40);const y=210+(n*29)%290+Math.cos(clock*.6+n)*15;ellipse(x,y,1.2,1.2,'#f3d29255');}}
}
function platform(p){const x=p.x-camera,y=p.y;if(x+p.w<-50||x>W+50)return;const pal=WORLDS[LEVELS[index].w],active=RoadEngine.solid(p,state);ctx.save();ctx.globalAlpha=active?1:.22;if(p.fall)ctx.translate(0,p.fall*70);if(p.type==='phase'||p.type==='gate'){ctx.strokeStyle=p.type==='phase'?(p.phase?'#b4a1dc':'#eccc97'):'#e1ba85';ctx.lineWidth=2;ctx.setLineDash(active?[]:[7,6]);ctx.strokeRect(x,y,p.w,20);ctx.setLineDash([]);ctx.fillStyle=p.phase?'#867baf55':'#bd9b6455';ctx.fillRect(x,y,p.w,20);}else{path([[x,y],[x+p.w,y],[x+p.w-8,y+28],[x+p.w*.77,y+35],[x+p.w*.5,y+32],[x+10,y+28]],pal.land);ctx.fillStyle=LEVELS[index].w===3?'#b08d74':'#88947d';ctx.fillRect(x,y,p.w,4);for(let j=8;j<p.w;j+=22){line(x+j,y+9,x+j-4,y+21,'#111f3033',1);if(LEVELS[index].w!==3)line(x+j,y,x+j+4,y-4,'#adb08c77',1);}if(p.type==='crumble'){for(let j=20;j<p.w;j+=45){line(x+j,y+2,x+j+8,y+12,'#dfb89c',1);line(x+j+8,y+12,x+j+3,y+23,'#dfb89c',1);}if(p.timer)ctx.translate(Math.sin(clock*70)*2,0);}if(p.type==='moving'){ctx.fillStyle=LEVELS[index].w===1?'#925e61':'#9b7d62';ctx.fillRect(x+4,y+5,p.w-8,16);for(let j=12;j<p.w-15;j+=28){ctx.fillStyle='#f8cd9460';ctx.fillRect(x+j,y+7,18,9);}ellipse(x+20,y+25,6,6,'#20323e');ellipse(x+p.w-20,y+25,6,6,'#20323e');line(x+p.w/2,y-15,x+p.w/2,y,'#c9b59a77',2);}}
 if(p.w>350){for(let j=0;j<2;j++){const tx=x+55+j*300;line(tx,y+25,tx-6,y+58,'#41515477',3);} }ctx.restore();}
function star(x,y,size=10){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(clock)*.1);path([[0,-size],[size*.3,-size*.3],[size,0],[size*.3,size*.3],[0,size],[-size*.3,size*.3],[-size,0],[-size*.3,-size*.3]],'#f8d28e');ctx.restore();}
function drawObject(o){const x=o.x-camera,y=o.y;if(x<-160||x>W+160)return;const selected=near===o;const lit=state.lights[o.n];
 if(o.type==='memory'){if(!objectAvailable(o))return;glow(x,y-28,35,.2);star(x,y-28+Math.sin(clock*2+o.n)*5,9);}
 if(o.type==='light'){lamp(x,y,!!lit,.55);if(!lit){glow(x,y-61,42,.15);star(x,y-64,5);}else text('✓',x+17,y-68,12);}
 if(o.type==='clock'&&objectAvailable(o)){line(x,y,x,y-66,'#6c777a',4);ellipse(x,y-66,15,15,'#24364b');ctx.strokeStyle='#d8ba8b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y-66,15,0,Math.PI*2);ctx.stroke();line(x,y-66,x+(state.phase?8:-8),y-74,'#e9c995',2);line(x,y-66,x,y-56,'#e9c995',1);text('◐',x,y-91,14);}
 if(o.type==='lever'){line(x,y,x,y-30,'#677878',5);line(x,y-30,x+(state.gates[o.n]?17:-17),y-55,'#edbd7d',4);ellipse(x+(state.gates[o.n]?17:-17),y-55,5,5,'#e8c497');}
 if(o.type==='table'){line(x-38,y-28,x-35,y,'#5a4340',5);line(x+38,y-28,x+35,y,'#5a4340',5);ctx.fillStyle='#bb9171';ctx.fillRect(x-58,y-34,116,8);ellipse(x-26,y-34,18,5,lit?'#d9ceae':'#6e696a');ellipse(x+25,y-34,18,5,lit?'#ab7550':'#6e696a');if(index!==10||state.phase===0)star(x+4,y-42,5);else{ctx.fillStyle='#7da1b4';ctx.fillRect(x+38,y-34,10,29);}if(lit)glow(x,y-42,60,.15);}
 if(o.type==='exit'){const ready=Object.keys(state.lights).length===3;glow(x,y-60,100,ready?.28:.08);ctx.strokeStyle=ready?'#f2cb90':'#87909c';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-33,y);ctx.lineTo(x-33,y-86);ctx.bezierCurveTo(x-33,y-132,x+33,y-132,x+33,y-86);ctx.lineTo(x+33,y);ctx.stroke();for(let n=0;n<3;n++){ellipse(x-18+n*18,y-97,4,4,state.lights[n]?'#f6cd88':'#5c6777');}text(index===14?'SON GEÇİT':'YOL DEVAM EDİYOR',x,y-139,9);}
 if(selected){text('✧',x,y-100,18);}
}
function render(){ctx.setTransform(scale,0,0,scale,0,0);const isHome=mode==='home'||(!world&&mode==='modal')||ending||(sceneKey==='14:outro'&&sceneLine>=1)||(sceneKey==='0:intro'&&sceneLine<5);const def=isHome?LEVELS[0]:LEVELS[index];backdrop(def,isHome?0:camera,isHome);if(!isHome&&world){for(const p of world.platforms)platform(p);for(let n=0;n<world.checkpoints.length;n++){const cp=world.checkpoints[n],x=cp.x-camera;if(x>-80&&x<W+80){line(x,442,x,416,'#e0b98566',2);if(n<=checkpoint)glow(x,432,32,.12);}}for(const o of world.objects)drawObject(o);if(index===2){const x=world.width-300-camera;bench(x,425,.8);character(x-20,423,'sen',1,false,true,.4);character(x+23,423,'damla',-1,false,true,.4);}if(index===5){const x=world.width-125-camera;character(x,442,'sen',-1,false,false,.6);}character(player.x-camera+13,player.y+player.h,actor,player.facing,mode==='play'&&Math.abs(player.vx)>15);if(['water','lantern'].includes(def.mechanic)){const y=518+Math.sin(state.time*.45)*28;const g=ctx.createLinearGradient(0,y,0,600);g.addColorStop(0,'#8db7b77a');g.addColorStop(1,'#244757ee');ctx.fillStyle=g;ctx.fillRect(0,y,W,600-y);for(let n=0;n<15;n++)line((n*87+clock*15)%W,y+10+(n%5)*14,(n*87+clock*15)%W+32,y+10+(n%5)*14,'#d6e7dd33');}const f=ctx.createLinearGradient(0,490,0,600);f.addColorStop(0,'#10213300');f.addColorStop(1,'#102133ee');ctx.fillStyle=f;ctx.fillRect(0,490,W,110);}if(flash>0){ctx.fillStyle=`rgba(242,212,171,${flash*.6})`;ctx.fillRect(0,0,W,H);}const vignette=ctx.createRadialGradient(W/2,280,180,W/2,280,Math.max(W*.65,500));vignette.addColorStop(0,'#06132000');vignette.addColorStop(1,'#06132066');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);}
function frame(t){const dt=Math.min((t-last)/1000||.016,.05);last=t;if(!document.hidden){clock+=dt;flash=Math.max(0,flash-dt);if(mode==='play'){accum+=dt;while(accum>=1/120){update(1/120);accum-=1/120;}}else accum=0;render();ambience();}requestAnimationFrame(frame);}
function bindHold(id,key){const el=$(id);const pointers=new Set();el.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='play')return;pointers.add(e.pointerId);el.setPointerCapture(e.pointerId);if(key==='jump'&&!input.jump)input.jumpPressed=true;input[key]=true;el.classList.add('held');soundStart();});const release=e=>{pointers.delete(e.pointerId);if(!pointers.size){input[key]=false;el.classList.remove('held');}};el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release);el.addEventListener('lostpointercapture',release);}
bindHold('left','left');bindHold('right','right');bindHold('jump','jump');
$('musicUnlock').onclick=()=>soundStart();$('interact').onclick=interact;$('pause').onclick=pause;$('start').onclick=()=>startLevel(0);$('continue').onclick=()=>startLevel(save.current,true);$('chapters').onclick=()=>chapterMenu('home');$('about').onclick=about;$('closeModal').onclick=closeModal;$('nextLine').onclick=nextLine;$('skipScene').onclick=finishScene;$('portraitContinue').onclick=()=>{portraitAllowed=true;$('rotate').hidden=true;};$('homeSound').onclick=()=>{save.volume=save.volume>0?0:.4;soundStart();store();$('homeSound').textContent=save.volume?'♫ Ses açık':'♫ Ses kapalı';};
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const key={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump'}[e.code];if(key){e.preventDefault();if(mode==='play'){if(key==='jump'&&!input.jump)input.jumpPressed=true;input[key]=true;}}if(e.repeat)return;if(e.code==='KeyE'){e.preventDefault();interact();}if(e.code==='Enter'&&mode==='scene')nextLine();if(e.code==='Escape'){if(mode==='modal')closeModal();else pause();}});
document.addEventListener('keyup',e=>{const key={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump'}[e.code];if(key)input[key]=false;});
window.addEventListener('blur',()=>{clearInput();if(mode==='play'||mode==='scene')pause();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){if(music)music.stop();persist();pause();if(audioContext)audioContext.suspend().catch(()=>{});} });window.addEventListener('pagehide',()=>{persist();if(music)music.stop();});window.addEventListener('resize',resize);document.addEventListener('contextmenu',e=>e.preventDefault());
resize();$('continue').hidden=!Object.keys(save.states).length;$('start').hidden=Object.keys(save.states).length>0;$('homeSound').textContent=save.volume?'♫ Ses açık':'♫ Ses kapalı';requestAnimationFrame(frame);
})();

