'use strict';
(()=>{
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const STORE='sana-gelen-yol-v1',LAST=LEVELS.length-1;
let save=RoadProgress.fresh(),storageOK=true,migrated=false;
try{const loaded=RoadProgress.migrate(JSON.parse(localStorage.getItem(STORE)),LEVELS);save=loaded.save;migrated=loaded.migrated;}catch{storageOK=false;}
let film=null,challenge=null;
let mode='home',priorMode='home',index=0,world,player,actor='sen',state,checkpoint=0,camera=0,W=1000,H=600,scale=1,clock=0,last=0,accum=0,near=null,deaths=0,flash=0,scene=null,sceneLine=0,sceneDone=null,sceneKey=null,sceneStart=0,ending=false,portraitAllowed=false;
const input={left:false,right:false,jump:false,jumpPressed:false};
let audioContext,gain,nextNote=0,noteIndex=0,music;
function store(){try{localStorage.setItem(STORE,JSON.stringify(save));}catch{if(storageOK)toast('Bu tarayıcı kayıt tutamıyor. İlerleme açık oturumda kalacak.');storageOK=false;}}
function persist(){if(world&&state){save.current=index;save.states[index]={checkpoint,phase:state.phase,tasks:state.tasks,tables:state.tables,drinks:state.drinks,coffee:state.coffee,actor};}store();}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
function clearInput(){for(const k in input)input[k]=false;document.querySelectorAll('.held').forEach(e=>e.classList.remove('held'));}
function selectedTrack(){if(mode==='home')return null;if(ending&&!scene&&!film)return RoadMusic.chapters[LAST];return RoadMusic.chapters[film?.chapter??(sceneKey?Number(sceneKey.split(':')[0]):index)];}
function syncMusic(gesture=false){if(!music)return;const track=selectedTrack();music.sync({track,playing:!document.hidden&&(['play','scene','film','ending'].includes(mode)||(ending&&mode==='modal'&&$('modalTitle').textContent!=='Yol burada bekler.')),volume:save.volume,duck:mode==='scene'||(ending&&mode==='modal'),gesture});$('musicUnlock').hidden=!music.blocked||mode==='modal'||mode==='home'||document.hidden||!save.volume;}
function soundStart(){try{if(!audioContext){audioContext=new(window.AudioContext||window.webkitAudioContext)();gain=audioContext.createGain();gain.connect(audioContext.destination);}gain.gain.value=save.volume;if(!document.hidden)audioContext.resume().catch(()=>{});}catch{}if(!music)music=RoadMusic.create({element:$('soundtrack'),context:audioContext,onBlocked:blocked=>{$('musicUnlock').hidden=!blocked||mode==='modal'||!save.volume;},onError:()=>toast('Müzik yüklenemedi. Yoluna devam edebilirsin.')});syncMusic(true);}
function tone(freq,duration=.8,vol=.1,type='sine'){if(!audioContext||audioContext.state!=='running'||!gain)return;const t=audioContext.currentTime,o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(gain);o.start();o.stop(t+duration+.02);}
function ambience(){syncMusic();if(selectedTrack()&&!music?.failed)return;if(document.hidden||mode==='paused'||mode==='modal'||!audioContext)return;if(clock>nextNote){nextNote=clock+(ending?3.5:1.7);if(!ending){const seq=[220,329.63,293.66,0,261.63,329.63,196,0];const f=seq[noteIndex++%8];if(f)tone(f*(index>11?.75:1),2.4,.045);}else tone(1300+Math.sin(clock)*130,.09,.007);}}
function resize(){const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';H=600;W=innerWidth/innerHeight*H;scale=canvas.height/H;orientation();}
function orientation(){const show=innerHeight>innerWidth&&!portraitAllowed&&mode!=='home'&&mode!=='modal';$('rotate').hidden=!show;if(show&&mode==='play')pause();}
function hud(){const d=LEVELS[index];$('worldLabel').textContent=WORLDS[d.w].short+' / '+String(index+1).padStart(2,'0')+' — '+LEVELS.length;$('levelLabel').textContent=d.title;$('actorLabel').textContent=actor==='damla'?'DAMLA':'SEN';$('memoryCount').textContent='✧ '+save.memories.length;$('routeCount').textContent=(world?.required.filter(k=>state?.tasks[k]).length||0)+'/'+(world?.required.length||0)+' HAZIR';$('objective').textContent=world?.goal||d.goal;}
function startLevel(i,resume=false){index=i;ending=false;film=null;challenge=null;$('cinema').hidden=true;$('endingMenu').hidden=true;actor=LEVELS[i].actor;world=RoadEngine.makeLevel(i,LEVELS[i]);const old=resume?save.states[i]:null;state={time:0,phase:old?.phase||0,tasks:{...(old?.tasks||{})},tables:{...(old?.tables||{})},drinks:{...(old?.drinks||{})},coffee:{...(old?.coffee||{})},assist:save.assist};checkpoint=Math.min(old?.checkpoint||0,world.checkpoints.length-1);actor=old?.actor||actor;const cp=world.checkpoints[checkpoint]||world.checkpoints[0];player=RoadEngine.createPlayer(cp.x,cp.y);camera=Math.max(0,player.x-W*.32);deaths=0;mode='play';priorMode='play';$('modal').hidden=true;$('home').hidden=true;$('hud').hidden=false;$('controls').hidden=false;$('objective').hidden=false;clearInput();hud();persist();soundStart();orientation();if(!resume||!save.seen.includes(i+':intro'))showScene(LEVELS[i].intro,()=>{orientation();},i+':intro');}
function showScene(lines,done=()=>{},key=null){clearInput();scene=lines;sceneLine=0;sceneDone=done;sceneKey=key;sceneStart=clock;mode='scene';soundStart();$('dialogue').hidden=false;$('controls').hidden=true;showLine();}
function showLine(){const l=scene[sceneLine];const who=l[0]==='SEN'?'sen':l[0]==='DAMLA'?'damla':null;$('portrait').hidden=!who;$('dialogue').classList.toggle('has-portrait',!!who);$('dialogue').classList.toggle('poetry',l[0].startsWith('İSMET ÖZEL')); if(who)RoadCharacters.portrait($('portrait'),who);syncMusic(true);$('speaker').textContent=l[0];$('line').textContent=l[1];$('lineCount').textContent=String(sceneLine+1).padStart(2,'0')+' / '+String(scene.length).padStart(2,'0');$('nextLine').textContent=sceneLine===scene.length-1?'Yola devam →':'Devam →';tone(440,.1,.008);}
function finishScene(){if(sceneKey&&!save.seen.includes(sceneKey)){save.seen.push(sceneKey);store();}const fn=sceneDone;scene=null;sceneKey=null;$('dialogue').hidden=true;mode='play';$('controls').hidden=false;clearInput();fn();}
function nextLine(){if(!scene||mode!=='scene')return;if(sceneKey==='0:intro'&&sceneLine===4){sceneLine++;playFilm({...RoadCinema.rupture(),chapter:0},()=>{mode='scene';$('dialogue').hidden=false;showLine();},'0:rupture');return;}if(++sceneLine>=scene.length)finishScene();else showLine();}
function playFilm(spec,done=()=>{},key=null){clearInput();challenge=null;film={...spec,time:0,done,key,chapter:spec.chapter??index};mode='film';$('dialogue').hidden=true;$('controls').hidden=true;$('hud').hidden=true;$('objective').hidden=true;$('modal').hidden=true;$('cinema').hidden=false;$('filmTitle').textContent=spec.title;$('filmCaption').textContent=spec.caption;$('filmProgress').style.width='0%';soundStart();}
function finishFilm(){if(!film)return;const f=film;film=null;if(f.key&&!save.seen.includes(f.key)){save.seen.push(f.key);store();}$('cinema').hidden=true;mode='play';$('hud').hidden=!world;$('objective').hidden=!world;$('controls').hidden=!world;clearInput();f.done();syncMusic(true);}
function advanceFilm(dt){if(mode!=='film'||!film)return;const old=film.time;film.time+=dt;if(film.kind==='rupture'&&old<3&&film.time>=3)tone(62,1.8,.13,'triangle');$('filmProgress').style.width=Math.min(100,film.time/film.duration*100)+'%';if(film.time>=film.duration)finishFilm();}
function cancelNarrative(){film=null;scene=null;challenge=null;$('cinema').hidden=true;$('dialogue').hidden=true;mode='play';$('hud').hidden=false;$('controls').hidden=false;$('objective').hidden=false;}
function openModal(title,body,returnMode=mode){priorMode=returnMode;mode='modal';clearInput();$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').hidden=false;$('controls').hidden=true;syncMusic();}
function closeModal(){ challenge=null;$('modal').hidden=true;mode=priorMode;clearInput();$('controls').hidden=mode!=='play';soundStart();orientation();}
function menuButton(text,fn,primary=false){const b=document.createElement('button');b.textContent=text;b.className=primary?'primary':'secondary';b.onclick=fn;return b;}
function addButtons(actions){const row=document.createElement('div');row.className='menu-buttons';for(const [text,fn,primary]of actions)row.append(menuButton(text,fn,primary));$('modalBody').append(row);}
function pause(){if(!['play','scene','film','ending'].includes(mode))return;const ret=mode;persist();openModal('Yol burada bekler.',`<p>İlerlemen bu cihazda otomatik kaydediliyor. Acele etmene gerek yok.</p><div class="settings"><label>Ses <input id="volume" type="range" min="0" max="1" step=".05" value="${save.volume}" aria-label="Ses seviyesi"></label><label><input id="assist" type="checkbox" ${save.assist?'checked':''}> Kolaylaştırılmış zıplama</label></div>`,ret);$('volume').oninput=e=>{save.volume=+e.target.value;if(gain)gain.gain.value=save.volume;syncMusic(true);store();};$('assist').onchange=e=>{save.assist=e.target.checked;if(state)state.assist=save.assist;store();};addButtons([['Devam et',closeModal,true],['Bölümü baştan oyna',()=>startLevel(index)],['Kontrol noktasına dön',()=>{closeModal();if(!world){home();return;}cancelNarrative();respawn(false);}],['Bölümler ve anılar',()=>chapterMenu(ret)],['Ana menü',home]]);}
function home(){persist();film=null;challenge=null;$('cinema').hidden=true;$('endingMenu').hidden=true;mode='home';scene=null;ending=false;$('dialogue').hidden=true;$('modal').hidden=true;$('hud').hidden=true;$('objective').hidden=true;$('controls').hidden=true;$('home').hidden=false;$('rotate').hidden=true;$('continue').hidden=!Object.keys(save.states).length;$('start').hidden=Object.keys(save.states).length>0;clearInput();syncMusic();}
function about(){openModal('Bir insana çıkan yollar.',`<p>Damla ve senin hikâyenden beslenen, altı dünyada geçen bir yolculuk. Karakterler gönderdiğiniz fotoğraflardaki saç, yüz ve kıyafet ayrıntıları esas alınarak yeniden çizildi. Gerçek olarak belirtilmeyen konuşmalar, mekân ayrıntıları ve final repliği bu oyun için yazılmış kurgu.</p><p>Bu sürüm 16 bölüm içerir. Koru’daki yarılma ve bölüm geçişleri otomatik oynayan, duraklatılıp atlanabilen animasyonlardır. Siyah beyaz kayıtlar anılardan esinlenen çizim canlandırmalarıdır. 1,5–2 saatlik hedef süre henüz oyuncu testleriyle doğrulanmadı.</p><p>“Şamdanları Donanınca” bir ses anısı olarak anılır; şarkının kaydı, sözleri veya melodisi kullanılmaz. 16 bölümün tamamında gönderdiğiniz üç kayıttan biri çalar: Yann Tiersen — Naval; Jóhann Jóhannsson — The Rocket Builder; Max Richter — On the Nature of Daylight. Geçişlerde İsmet Özel’den kısa alıntılar ve bunlara karşılık yazılmış özgün konuşmalar bulunur. <a href="https://github.com/camabdullah/asdf/blob/main/POETRY.md" target="_blank" rel="noopener">Şiirler ve kaynakları ↗</a></p><p class="note">Telefonda yatay tut: solda yönler, sağda zıplama. Daha yüksek atlamak için zıplamayı basılı tut. Altın işaretlere yaklaşınca ✧ görünür. Bilgisayarda A/D veya ←/→, Boşluk ile zıpla, E ile etkileş. Esc duraklatır.</p><p>Kayıt aynı cihaz ve tarayıcıda saklanır. Verileri silmek ilerlemeyi silebilir. Düşmek hikâyeyi değiştirmez; son kontrol noktasından devam edersin.</p>`);}
function chapterMenu(ret=mode){openModal('Geçtiğin yollar.',`<p>Tamamladığın bölümleri yeniden oyna; gördüğün sahneleri tekrar izle.</p>`,ret);for(let w=0;w<WORLDS.length;w++){const title=document.createElement('div');title.className='world-title';title.textContent=WORLDS[w].name.toLocaleUpperCase('tr');$('modalBody').append(title);const grid=document.createElement('div');grid.className='chapter-grid';for(let n=0;n<LEVELS.length;n++){if(LEVELS[n].w!==w)continue;const b=menuButton('',()=>{if(save.completed.includes(n))startLevel(n);else if(save.states[n])startLevel(n,true);else startLevel(n);});b.className='chapter-tile';b.disabled=n>save.unlocked;b.innerHTML=`<span>${String(n+1).padStart(2,'0')} ${save.completed.includes(n)?'✓ TAMAMLANDI':n>save.unlocked?'· KİLİTLİ':''}</span><strong>${LEVELS[n].title}</strong>`;grid.append(b);}$('modalBody').append(grid);}addButtons([['Anı defteri',()=>memoryMenu(ret)],['İzlenen sahneler',()=>sceneMenu(ret)]]);}
function memoryMenu(ret){openModal('Yanına aldıkların.',`<p>${save.memories.length} / ${LEVELS.length} anı parçası. Anıları toplamak finali değiştirmez.</p>`,ret);for(let i=0;i<LEVELS.length;i++)if(save.memories.some(v=>v.startsWith(i+':'))){const e=document.createElement('div');e.className='memory-entry';e.innerHTML='<strong>'+LEVELS[i].memory[0]+'</strong><p>'+LEVELS[i].memory[1]+'</p>';$('modalBody').append(e);}if(!save.memories.length)$('modalBody').innerHTML+='<p>Işıktan yapılmış küçük yıldızlar, ana yolun üstündeki gizli platformlarda seni bekler.</p>';}
function sceneMenu(ret){const original={scene,sceneLine,sceneDone,sceneKey,film};openModal('Hatırlanan sahneler.','<p>Gördüğün konuşmaları ve animasyonları yeniden izle.</p>',ret);for(const key of save.seen){const [n,part]=key.split(':');if(!LEVELS[n])continue;const label={intro:'Açılış',outro:'Kapanış',film:'Geçiş filmi',rupture:'Yolların yarılması'}[part];if(!label)continue;const restore=()=>{scene=original.scene;sceneLine=original.sceneLine;sceneDone=original.sceneDone;sceneKey=original.sceneKey;film=original.film;if(scene){$('dialogue').hidden=false;showLine();}mode=ret;$('cinema').hidden=!film;sceneMenu(ret);};const b=menuButton((+n+1)+'. '+LEVELS[n].title+' · '+label,()=>{$('modal').hidden=true;film=null;$('cinema').hidden=true;if(part==='film'||part==='rupture')playFilm({...part==='rupture'?RoadCinema.rupture():RoadCinema.transition(+n,LEVELS[n]),chapter:+n},restore);else showScene(LEVELS[n][part],restore,key);});b.style.margin='5px';$('modalBody').append(b);}}
function respawn(count=true){const cp=world.checkpoints[checkpoint];player=RoadEngine.createPlayer(cp.x,cp.y);RoadEngine.resetPlatforms(world,state);clearInput();flash=.4;if(count){deaths++;tone(110,.25,.08);toast('Yol bitmedi. Son ışığından devam.');if(deaths===4&&!save.assist){openModal('Biraz daha kolay olsun mu?','<p>Bu engelde birkaç kez düştün. Zıplama yardımını açabilirsin; hikâye ve final değişmez.</p>','play');addButtons([['Yardımı aç',()=>{save.assist=true;state.assist=true;store();closeModal();},true],['Kendim deneyeceğim',closeModal]]);}}camera=Math.max(0,player.x-W*.32);}
function objectAvailable(o){if(o.type==='beacon')return false;if(o.type==='memory')return !save.memories.includes(index+':'+o.id);if(o.key)return !state.tasks[o.key];return true;}
function interact(){if(mode!=='play'||!near)return;const o=near;if(!objectAvailable(o))return;
 if(o.type==='memory'){save.memories.push(index+':'+o.id);store();hud();tone(659,1,.09);showScene([['BİR ANI · '+LEVELS[index].memory[0],LEVELS[index].memory[1]]]);return;}
 if(o.type==='clock'){state.phase=1-state.phase;persist();flash=.2;toast(state.phase?'Öteki akşam · mor yollar katı':'İlk akşam · altın yollar katı');tone(state.phase?392:330,.5,.06);return;}
 if(o.type==='align'&&state.phase!==1){toast('Köprü saati mor akşamı gösteriyor. Önce yanındaki saati değiştir.');return;}
 if(o.type==='table'){tablePuzzle(o);return;}
 if(o.type==='coffee'){coffeePuzzle(o);return;}
 if(o.type==='dial'||o.type==='brew'){if(o.type==='brew'&&(!state.tasks['latte-order']||!state.tasks.pressure)){toast('Önce iki latteyi seç ve buhar vanasını aç.');return;}timingPuzzle(o);return;}
 if(o.type==='serve'){if(!state.tasks['latte-brew']){toast('Önce iki fincanı makinede hazırla.');return;}playFilm({kind:'coffee',duration:9,title:'İki laktozsuz latte.',caption:'Biri sana, biri Damla’ya. Pencerenin önünde biraz daha zaman.'},()=>activate(o));return;}
 if(o.key){activate(o);return;}
 if(o.type==='exit'){
  const missing=world.required.filter(k=>!state.tasks[k]);if(missing.length){toast('Eksik: '+missing.map(k=>k==='crate'?'Sandığı plakaya it':world.objects.find(o=>o.key===k)?.label).join(' · '));return;}
  if(index===LAST){openModal('Son bağlantı.',`<p>Geçit açık kalırsa Damla aynı anılara dönecek. Kapatırsan onun çıkışı açılacak ve aranızdaki son yol kesilecek.</p><p>İkiniz de yaşayacak, ikiniz de devam edebileceksiniz. Yollarınız birleşmeyecek.</p>`,'play');addButtons([['Geçidi kapat',()=>{$('modal').hidden=true;complete();},true],['Biraz daha burada kal',closeModal]]);}else complete();
 }
}
function activate(o){state.tasks[o.key]=true;if(LEVELS[index].mechanic==='relay'&&o.n===0)actor='damla';persist();hud();tone(523,.8,.1);showScene(o.lines||[LEVELS[index].signs[o.n]],()=>{if(actor==='damla'&&LEVELS[index].mechanic==='relay')toast('Şimdi Damla’nın yolundasın.');});}
function tablePuzzle(o){let pair=[...(state.tables[o.n]||[0,0])],drinks=[...(state.drinks[o.n]||[0,0])];const names=['Barbeküs','Kremantar','Köri'],drinkNames=['Ayran','Sipariş yok','Su'];openModal('Her zamankinden.',`<p>Damla’ya Kremantar, sana Barbeküs. İçecek siparişini de hatırla: Damla ayran söylemez; seninkinden içer.</p><div class="menu-buttons"><button class="secondary" id="dishLeft"></button><button class="secondary" id="dishRight"></button></div><div class="menu-buttons drink-row"><button class="secondary" id="drinkLeft"></button><button class="secondary" id="drinkRight"></button></div><p id="tableHint"></p>`,'play');const draw=()=>{$('dishLeft').textContent='Damla: '+names[pair[0]];$('dishRight').textContent='Sen: '+names[pair[1]];$('drinkLeft').textContent='Damla’nın içeceği: '+drinkNames[drinks[0]];$('drinkRight').textContent='Senin içeceğin: '+drinkNames[drinks[1]];$('tableHint').textContent=index===10?(state.phase===0?'Yıldızlı peçetenin olduğu akşam.':'Mavi atkı. Önce öteki akşama dön.'):'Masada tek ayran olacak.';};$('dishLeft').onclick=()=>{pair[0]=(pair[0]+1)%3;draw();};$('dishRight').onclick=()=>{pair[1]=(pair[1]+1)%3;draw();};$('drinkLeft').onclick=()=>{drinks[0]=(drinks[0]+1)%3;draw();};$('drinkRight').onclick=()=>{drinks[1]=(drinks[1]+1)%3;draw();};draw();addButtons([['Masayı hatırla',()=>{state.tables[o.n]=pair;state.drinks[o.n]=drinks;persist();if(RoadPuzzles.tableOK(pair,drinks,state.phase,index===10)){playFilm({kind:'ayran',duration:8,title:'Ben söylemeyeceğim, bir yudum alırım.',caption:'Sipariş sende. Kullanım ortak.'},()=>activate(o));}else{$('tableHint').textContent=index===10&&state.phase!==0?'Yıldızlı peçetenin olduğu akşama dön.':'Kremantar ve Barbeküs; Damla’ya içecek siparişi yok, sana bir ayran.';}},true],['Yola dön',closeModal]]);}
function coffeePuzzle(o){const order={drink:0,milk:0,cups:1,...state.coffee},drinks=['Americano','Latte','Cappuccino'],milks=['Normal süt','Laktozsuz süt','Yulaf sütü'];openModal('Her ikimize de aynı kahve.', '<p>İkiniz Caffelab’da hep ne içerdiniz? İçeceği, sütü ve fincan sayısını seç.</p><div class="menu-buttons"><button id="coffeeDrink" class="secondary"></button><button id="coffeeMilk" class="secondary"></button><button id="coffeeCups" class="secondary"></button></div><p id="coffeeHint">İki kişinin siparişi tek tezgâhta hazırlanacak.</p>','play');const draw=()=>{$('coffeeDrink').textContent=drinks[order.drink];$('coffeeMilk').textContent=milks[order.milk];$('coffeeCups').textContent=order.cups+' fincan';};$('coffeeDrink').onclick=()=>{order.drink=(order.drink+1)%3;draw();};$('coffeeMilk').onclick=()=>{order.milk=(order.milk+1)%3;draw();};$('coffeeCups').onclick=()=>{order.cups=order.cups%3+1;draw();};draw();addButtons([['Siparişi hazırla',()=>{state.coffee=order;persist();if(RoadPuzzles.coffeeOK(order)){$('modal').hidden=true;activate(o);}else $('coffeeHint').textContent='İki latte; ikisinde de laktozsuz süt. Bir fincanı paylaşmıyordunuz.';},true],['Yola dön',closeModal]]);}
function timingPuzzle(o){openModal(o.type==='brew'?'Makinenin ritmi.':'Son halkanın ritmi.', '<p>İbre yeşil aralıktayken sabitle. '+(o.type==='brew'?'İki fincan için iki ayrı doğru zamanlama gerekiyor.':'Halka sabitlenince buradaki hatırayı dinleyebilirsin.')+'</p><div class="timing-track"><span class="timing-zone"></span><b id="timingNeedle"></b></div><p id="timingHint">Hazır olduğunda ritmi başlat.</p><div class="menu-buttons"><button id="timingStart" class="secondary">Ritmi başlat</button><button id="timingStop" class="primary">Şimdi sabitle</button></div>','play');challenge={o,time:0,hits:0,paused:true,target:o.type==='brew'?2:1};$('timingStop').disabled=true;$('timingStart').onclick=()=>{if(!challenge)return;challenge.paused=false;$('timingStart').disabled=true;$('timingStop').disabled=false;soundStart();};$('timingStop').onclick=()=>{const ch=challenge;if(!ch||ch.paused)return;if(RoadPuzzles.inWindow(ch.time)){ch.hits++;tone(620,.2,.06);if(ch.hits===ch.target){const o=ch.o;challenge=null;$('modal').hidden=true;activate(o);}else{ch.time=0;ch.paused=true;$('timingHint').textContent='İlk latte hazır. İkinci fincan için yeniden başlat.';$('timingStart').disabled=false;$('timingStart').textContent='İkinci fincan';$('timingStop').disabled=true;}}else{ch.hits=0;$('timingHint').textContent='Basınç kaçtı. İbre yeniden yeşile geldiğinde dene.';tone(135,.15,.045);}};}
function updateChallenge(dt){if(!challenge||mode!=='modal'||challenge.paused)return;challenge.time+=dt;$('timingNeedle').style.left=RoadPuzzles.needle(challenge.time)*100+'%';}
function suspendChallenge(){if(!challenge)return;challenge.paused=true;$('timingStart').disabled=false;$('timingStart').textContent='Ritmi sürdür';$('timingStop').disabled=true;}
function nextChapterMenu(){openModal('Bir sonraki iz.', '<p>'+(index+1)+'. bölüm tamamlandı.</p><p>Sıradaki: <strong>'+LEVELS[index+1].title+'</strong></p>','play');addButtons([['Yola devam',()=>startLevel(index+1),true],['Bölümler',()=>chapterMenu('play')],['Ana menü',home]]);}
function endingMenu(){openModal('Sana Gelen Yol','<p>Damla yoluna devam ediyor. Sen de.</p><p>Yanında kalan '+save.memories.length+' anı var. Müzik sürüyor; burada istediğin kadar oturabilirsin.</p>','ending');addButtons([['Biraz daha otur',closeModal,true],['Anı defteri',()=>memoryMenu('ending')],['Ana menü',home]]);}

function complete(){const d=LEVELS[index];if(!save.completed.includes(index))save.completed.push(index);save.unlocked=Math.max(save.unlocked,Math.min(index+1,LAST));persist();showScene(d.outro,()=>{if(index===LAST){ending=true;mode='ending';$('hud').hidden=true;$('objective').hidden=true;$('controls').hidden=true;$('endingMenu').hidden=false;syncMusic(true);}else playFilm(RoadCinema.transition(index,d),nextChapterMenu,index+':film');},index+':outro');}
function update(dt){if(mode!=='play')return;state.time+=dt;state.jumped=false;const dead=RoadEngine.step(world,player,input,state,dt);input.jumpPressed=false;if(state.jumped)tone(350,.13,.024);if(dead){respawn();return;}if(state.taskChanged){state.taskChanged=false;persist();hud();toast('Sandık yerine oturdu · Kapı açıldı');tone(523,.5,.08);}if(player.ground!==null){for(let n=0;n<world.checkpoints.length;n++){const cp=world.checkpoints[n];if(n>checkpoint&&player.ground===cp.platform){checkpoint=n;deaths=0;persist();toast('Kontrol noktası · Kaydedildi');tone(440,.4,.05);}}}near=null;let distance=95;for(const o of world.objects){if(!objectAvailable(o)||Math.abs(player.y+player.h-o.y)>(o.type==='memory'?42:64))continue;const dist=Math.hypot(player.x+13-o.x,(player.y+player.h)-(o.y));if(dist<distance){near=o;distance=dist;}}$('interact').hidden=!near;if(near){const labels={memory:'Anıyı al',light:actor==='damla'?(index===8&&near.n===2?'Notu bırak':'Işığı yak'):'İzi oku',clock:'Zamanı değiştir',lever:'Kapıyı kapat',table:'Masaya bak',exit:index===LAST?'Son geçit':'Yola devam'};$('interactLabel').textContent=near.label||labels[near.type];}const breeze=RoadEngine.wind(world,state);$('windIndicator').hidden=!breeze;$('windIndicator').textContent=(breeze<0?'←':'→')+' RÜZGÂR '+(Math.abs(breeze)>38?'GÜÇLÜ':'HAFİF');const target=Math.max(0,Math.min(world.width-W,player.x-W*.32));camera+=(target-camera)*Math.min(1,dt*5);$('progressFill').style.width=Math.max(0,Math.min(100,player.x/world.width*100))+'%';save.minutes+=dt/60;}
// Painted vector scenery and photo-referenced characters; music loads per chapter.
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function path(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();}
function line(x,y,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function glow(x,y,r,alpha=.22){const g=ctx.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,`rgba(255,217,151,${alpha})`);g.addColorStop(1,'rgba(255,198,110,0)');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function text(str,x,y,size=12,color='#e9c995',align='center'){ctx.fillStyle=color;ctx.textAlign=align;ctx.font=size+'px system-ui';ctx.fillText(str,x,y);}
function tree(x,y,s,tint,seed=0){ctx.save();ctx.translate(x,y);ctx.scale(s,s);path([[-12,0],[-7,-149],[-42,-217],[-25,-215],[2,-163],[28,-237],[36,-230],[9,-119],[15,0]],'#243b43');for(let j=0;j<37;j++){const a=j*2.399+seed,rx=Math.sin(j*3.7+seed)*68,ry=-205+Math.cos(j*1.7+seed)*50;ellipse(rx,ry,40+Math.sin(a)*12,22+Math.cos(a)*9,tint);if(j%4===0)ellipse(rx-3,ry-4,30,12,'#dfbc8112');}ctx.restore();}
function bench(x,y,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);line(-53,-12,-50,16,'#182832',5);line(54,-12,51,16,'#182832',5);for(let n=0;n<4;n++){ctx.fillStyle=n===3?'#b08b68':'#927255';ctx.fillRect(-66,-45+n*11,133,7);}ctx.fillStyle='#c6a07b';ctx.fillRect(-73,-5,147,7);line(-57,-51,-57,-1,'#243337',4);line(60,-51,60,-1,'#243337',4);ctx.restore();}
function lamp(x,y,lit=true,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);if(lit)glow(0,-115,85,.2);line(0,0,0,-116,'#27333a',5);line(-17,-128,17,-128,'#27333a',5);path([[-20,-129],[0,-142],[20,-129]],'#27333a');ctx.fillStyle=lit?'#ffe2a3':'#697b87';ctx.fillRect(-11,-123,22,24);line(-12,-126,-9,-97,'#29343a',3);line(12,-126,9,-97,'#29343a',3);ctx.fillStyle='#29343a';ctx.fillRect(-13,-100,26,4);ctx.restore();}
function character(x,y,who='sen',facing=1,moving=false,seated=false,alpha=1){RoadCharacters.draw(ctx,{x,y,who,facing,moving,seated,alpha,time:clock,steps:player?.steps||0});}
function backdrop(def,cam=0,isHome=false){const pal=WORLDS[def.w],phase=state?.phase||0;const g=ctx.createLinearGradient(0,0,0,530);g.addColorStop(0,pal.sky[0]);g.addColorStop(.62,pal.sky[1]);g.addColorStop(1,pal.sky[2]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(phase&&['phase','compare','mixed'].includes(def.mechanic)){ctx.fillStyle='#30256355';ctx.fillRect(0,0,W,H);}const sunX=W*.73-cam*.015;glow(sunX,214,210,.13);ellipse(sunX,214,33,33,'#f5cdaa55');for(let j=0;j<12;j++){const xx=((j*239.13-cam*.04)%(W+300)+W+300)%(W+300)-150;ellipse(xx,95+(j%4)*35,110,11,'#ead5c70a');}
 for(let layer=0;layer<3;layer++){const pts=[[0,600]];for(let x=-80;x<W+100;x+=35)pts.push([x,315+layer*53+Math.sin((x+cam*.1+layer*201)*.007)*28+Math.cos(x*.013+layer)*11]);pts.push([W+100,600]);path(pts,['#60758255','#425c6888','#2e4858'][layer]);}
 if(['city','end'].includes(pal.type)){for(let n=-1;n<14;n++){const x=n*123-(cam*.2%123),h=57+Math.sin(n*8.2)*30;ctx.fillStyle='#334759';ctx.fillRect(x,335-h,91,h+60);path([[x-4,335-h],[x+44,315-h],[x+96,335-h]],'#394c5d');for(let j=0;j<4;j++)for(let k=0;k<3;k++)ctx.fillStyle=(n+j+k)%4===0?'#d5ba7b88':'#70808a33',ctx.fillRect(x+12+j*20,345-h+k*21,8,12);}line(0,300,W,310,'#9da7a344',2);}
 if(pal.type==='cafe'||pal.type==='coffee'){ctx.fillStyle='#3b353a99';ctx.fillRect(0,80,W,360);for(let n=-1;n<10;n++){const x=n*220-(cam*.2%220);ctx.fillStyle='#d1a47a55';ctx.fillRect(x+30,136,145,216);for(let j=0;j<3;j++)line(x+40+j*50,138,x+40+j*50,350,'#433c40',6);line(x+30,240,x+175,240,'#433c40',5);line(x+100,80,x+100,137,'#b3a38d',2);glow(x+100,168,78,.22);path([[x+78,156],[x+88,140],[x+112,140],[x+122,156]],'#e2b282');}text(pal.type==='coffee'?'CAFFELAB':'TAVUK DÜNYASI',W*.62,108,13,'#f0c697');}
 for(let n=-1;n<9;n++){const x=n*260-(cam*.28%260);tree(x+90,444,.64,pal.leaf+'b0',n*4);}
 if(isHome){path([[0,469],[W*.42,451],[W*.68,430],[W,442],[W,600],[0,600]],'#314449');path([[0,531],[W*.37,481],[W*.75,445],[W,454],[W,483],[W*.7,473],[W*.35,520],[0,591]],'#b398773b');const bx=W*.73;tree(W*.97,480,1.9,'#314d4d',3);tree(W*.16,463,1.45,'#354e50',7);lamp(bx+115,440,true,1.16);bench(bx,445,1.1);character(bx-23,441,'sen',1,false,true);if(!ending&&!(sceneKey===LAST+':outro'&&sceneLine>=9))character(bx+30,441,'damla',-1,false,true);for(let n=0;n<52;n++){const x=(n*73.1)%W,y=460+(n*39.7)%140;line(x,y,x+Math.sin(n)*7,y-9,'#88917538',1);} }
 if(pal.type==='rain'){ctx.strokeStyle='#b8d2d333';ctx.lineWidth=1;for(let n=0;n<80;n++){const x=((n*67+clock*105)% (W+30))-15,y=(n*47+clock*340)%600;line(x,y,x-6,y+17,'#b8d2d330');}}else{for(let n=0;n<23;n++){const x=(n*97.5+Math.sin(clock*.4+n)*16-cam*.12)%(W+40);const y=210+(n*29)%290+Math.cos(clock*.6+n)*15;ellipse(x,y,1.2,1.2,'#f3d29255');}}
}
function platform(p){const x=p.x-camera,y=p.y;if(x+p.w<-50||x>W+50)return;const pal=WORLDS[LEVELS[index].w],active=RoadEngine.solid(p,state);ctx.save();ctx.globalAlpha=active?1:.22;if(p.fall)ctx.translate(0,p.fall*70);if(p.type==='phase'||p.type==='gate'){ctx.strokeStyle=p.type==='phase'?(p.phase?'#b4a1dc':'#eccc97'):'#e1ba85';ctx.lineWidth=2;ctx.setLineDash(active?[]:[7,6]);ctx.strokeRect(x,y,p.w,20);ctx.setLineDash([]);ctx.fillStyle=p.phase?'#867baf55':'#bd9b6455';ctx.fillRect(x,y,p.w,20);}else{path([[x,y],[x+p.w,y],[x+p.w-8,y+28],[x+p.w*.77,y+35],[x+p.w*.5,y+32],[x+10,y+28]],pal.land);ctx.fillStyle=[3,4].includes(LEVELS[index].w)?'#b08d74':'#88947d';ctx.fillRect(x,y,p.w,4);for(let j=8;j<p.w;j+=22){line(x+j,y+9,x+j-4,y+21,'#111f3033',1);if(![3,4].includes(LEVELS[index].w))line(x+j,y,x+j+4,y-4,'#adb08c77',1);}if(p.type==='crumble'){for(let j=20;j<p.w;j+=45){line(x+j,y+2,x+j+8,y+12,'#dfb89c',1);line(x+j+8,y+12,x+j+3,y+23,'#dfb89c',1);}if(p.timer)ctx.translate(Math.sin(clock*70)*2,0);}if(p.type==='moving'){ctx.fillStyle=LEVELS[index].w===1?'#925e61':'#9b7d62';ctx.fillRect(x+4,y+5,p.w-8,16);for(let j=12;j<p.w-15;j+=28){ctx.fillStyle='#f8cd9460';ctx.fillRect(x+j,y+7,18,9);}ellipse(x+20,y+25,6,6,'#20323e');ellipse(x+p.w-20,y+25,6,6,'#20323e');line(x+p.w/2,y-15,x+p.w/2,y,'#c9b59a77',2);}}

 if(['swing','moving','lift','raft'].includes(p.type)){
  if(p.type==='swing'){line(p.baseX-camera+p.w/2,p.baseY-130,x+12,y,'#c5b996',2);line(p.baseX-camera+p.w/2,p.baseY-130,x+p.w-12,y,'#c5b996',2);ellipse(p.baseX-camera+p.w/2,p.baseY-130,5,5,'#e7c896');}
  if(p.type==='lift'){line(x+p.w/2,p.baseY-85,x+p.w/2,p.baseY+90,'#d2b78560',3);text('↕',x+p.w/2,y+17,16);}
  if(p.type==='raft'){for(let k=8;k<p.w;k+=18){line(x+k,y+5,x+k,y+20,'#bead8966',2);}text('≈',x+p.w/2,y+38,20,'#afd4d1');}
  if(p.type==='moving'){line(p.baseX-camera-34,y+33,p.baseX-camera+p.w+34,y+33,'#caba8d66',2);}
 }
 if(p.type==='spring'){ctx.fillStyle='#524e52';ctx.fillRect(x+5,y+4,p.w-10,20);for(let k=10;k<p.w-10;k+=15)line(x+k,y+21,x+k+10,y+6,'#f7ca7d',2);ctx.fillStyle='#f3c172';ctx.fillRect(x,y,p.w,5);text('↑ BASILI TUT',x+p.w/2,y-12,10,'#ffdf9a');}
 if(p.type==='conveyor'){ctx.fillStyle='#343e4a';ctx.fillRect(x,y+4,p.w,19);for(let k=8;k<p.w-14;k+=27){const cx=x+8+((k+clock*p.belt*.3)%(p.w-20)+(p.w-20))%(p.w-20);text(p.belt>0?'›':'‹',cx,y+19,18,'#e7c48b');}ellipse(x+8,y+24,5,5,'#a7aeaa');ellipse(x+p.w-8,y+24,5,5,'#a7aeaa');}
 if(p.type==='gate'&&index===0&&active){ctx.fillStyle='#8e7057';ctx.fillRect(x,y+4,p.w,16);for(let k=12;k<p.w;k+=34)line(x+k,y+5,x+k+8,y+16,'#d8b88577',2);}
 if(p.w>350){for(let j=0;j<2;j++){const tx=x+55+j*300;line(tx,y+25,tx-6,y+58,'#41515477',3);} }ctx.restore();}

function drawMechanisms(){
 for(const h of world.hazards){const a=RoadEngine.hazard(h,state.time),x=h.x-camera;if(x<-180||x>W+180)continue;
  if(h.type==='steam'){ctx.fillStyle='#50636b';ctx.fillRect(x-22,h.y+2,44,14);for(let k=-16;k<=16;k+=8)line(x+k,h.y+4,x+k,h.y+12,'#182e3a',3);
   if(a.active){for(let k=0;k<7;k++){const rise=(clock*110+k*12)%75;ellipse(x+Math.sin(k+clock*8)*9,h.y-rise,7+rise*.13,10,'#e9e0d789');}text('BUHAR',x,h.y-91,9,'#f2cba5');}
   else if(a.warning){glow(x,h.y-9,28,.24);text('!',x,h.y-15,18,'#f7ba70');}else text('BEKLE · GEÇ',x,h.y+37,9,'#d7c2a5');
  }else{line(x,h.y-128,a.x-camera,a.y,'#a8a597',2);ellipse(x,h.y-128,5,5,'#c9b589');ellipse(a.x-camera,a.y,a.r,a.r,'#b26968');ellipse(a.x-camera-3,a.y-4,6,5,'#ebbd9755');text('SARKAÇ',x,h.y+37,9,'#d7c2a5');}
 }
 const c=world.crate;if(c){const lit=state.tasks.crate,x=c.x-camera,y=c.y;if(c.wall-camera>-80&&c.x-camera<W+80){ctx.fillStyle=lit?'#eacb8b':'#988e74';ctx.fillRect(c.plate-camera-28,c.floor-3,56,5);text(lit?'✓':'SANDIĞI İT →',c.plate-camera,c.floor+40,10);ctx.fillStyle='#88664c';ctx.fillRect(x,y,40,40);ctx.strokeStyle='#dab68a';ctx.lineWidth=2;ctx.strokeRect(x+3,y+3,34,34);line(x+5,y+5,x+35,y+35,'#c09a70',3);line(x+35,y+5,x+5,y+35,'#c09a70',3);const wx=c.wall-camera;line(wx,c.floor,wx,c.floor-128,'#667880',5);line(wx+14,c.floor,wx+14,c.floor-128,'#667880',5);if(!lit){for(let yy=c.floor-120;yy<c.floor;yy+=17)line(wx,yy,wx+14,yy,'#ddc3a1',4);}else glow(wx,c.floor-75,40,.13);}}
}
function star(x,y,size=10){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(clock)*.1);path([[0,-size],[size*.3,-size*.3],[size,0],[size*.3,size*.3],[0,size],[-size*.3,size*.3],[-size,0],[-size*.3,-size*.3]],'#f8d28e');ctx.restore();}
function drawObject(o){const x=o.x-camera,y=o.y;if(x<-160||x>W+160)return;const selected=near===o;const lit=!!state.tasks[o.key];
 if(o.type==='memory'){if(!objectAvailable(o))return;glow(x,y-28,35,.2);star(x,y-28+Math.sin(clock*2+o.n)*5,9);}
 if(o.type==='beacon')lamp(x,y,true,.6);
 if(o.type==='light'){lamp(x,y,!!lit,.55);if(!lit){glow(x,y-61,42,.15);star(x,y-64,5);}else text('✓',x+17,y-68,12);}
 if(o.type==='clock'&&objectAvailable(o)){line(x,y,x,y-66,'#6c777a',4);ellipse(x,y-66,15,15,'#24364b');ctx.strokeStyle='#d8ba8b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y-66,15,0,Math.PI*2);ctx.stroke();line(x,y-66,x+(state.phase?8:-8),y-74,'#e9c995',2);line(x,y-66,x,y-56,'#e9c995',1);text('◐',x,y-91,14);}
 if(['lever','switch','water','align','dial','brew'].includes(o.type)){line(x,y,x,y-30,'#677878',5);line(x,y-30,x+(state.tasks[o.key]?17:-17),y-55,'#edbd7d',4);ellipse(x+(state.tasks[o.key]?17:-17),y-55,5,5,'#e8c497');}
 if(o.type==='table'){line(x-38,y-28,x-35,y,'#5a4340',5);line(x+38,y-28,x+35,y,'#5a4340',5);ctx.fillStyle='#bb9171';ctx.fillRect(x-58,y-34,116,8);ellipse(x-26,y-34,18,5,lit?'#d9ceae':'#6e696a');ellipse(x+25,y-34,18,5,lit?'#ab7550':'#6e696a');if(index!==10||state.phase===0)star(x+4,y-42,5);else{ctx.fillStyle='#7da1b4';ctx.fillRect(x+38,y-34,10,29);}ctx.fillStyle='#d5e0d1';ctx.fillRect(x+39,y-53,12,18);ellipse(x+45,y-53,6,2,'#faf0d7');if(lit)glow(x,y-42,60,.15);}
 if(o.type==='brew'){ctx.fillStyle='#4c5e65';ctx.fillRect(x-40,y-75,80,75);ctx.fillStyle='#c6c2ae';ctx.fillRect(x-34,y-68,68,27);ellipse(x,y-55,10,10,'#263b43');line(x,y-55,x+Math.sin(clock*2)*7,y-62,'#e8c68d',2);for(let j=-1;j<=1;j+=2){line(x+j*18,y-37,x+j*18,y-20,'#d5c8b0',4);ctx.fillStyle='#e6d4b4';ctx.fillRect(x+j*18-7,y-18,14,15);}text('2 LATTE',x,y-87,9);}
 if(o.type==='coffee'||o.type==='serve'){ctx.fillStyle='#b08e6a';ctx.fillRect(x-52,y-34,104,8);line(x-43,y-25,x-43,y,'#675749',4);line(x+43,y-25,x+43,y,'#675749',4);for(let j=-1;j<=1;j+=2){ctx.fillStyle=lit?'#eedfc0':'#918675';ctx.fillRect(x+j*23-10,y-55,20,20);ellipse(x+j*23,y-55,10,3,'#e0c9a4');}text(o.type==='coffee'?'LAKTOZSUZ LATTE':'PENCERE MASASI',x,y-75,8);}
 if(o.type==='exit'){const ready=world.required.every(k=>state.tasks[k]);glow(x,y-60,100,ready?.28:.08);ctx.strokeStyle=ready?'#f2cb90':'#87909c';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-33,y);ctx.lineTo(x-33,y-86);ctx.bezierCurveTo(x-33,y-132,x+33,y-132,x+33,y-86);ctx.lineTo(x+33,y);ctx.stroke();world.required.forEach((k,n)=>ellipse(x+(n-(world.required.length-1)/2)*14,y-97,4,4,state.tasks[k]?'#f6cd88':'#5c6777'));text(index===LAST?'SON GEÇİT':'YOL DEVAM EDİYOR',x,y-139,9);}
 if(o.type==='note'){line(x,y,x,y-43,'#98795f',3);ctx.fillStyle=lit?'#907e68':'#f0d9ac';ctx.fillRect(x-16,y-65,32,26);for(let k=0;k<3;k++)line(x-10,y-58+k*6,x+9,y-58+k*6,'#977558',1);}
 if(o.type==='observe'||o.type==='echo'){bench(x,y-8,.65);if(lit)glow(x,y-45,40,.15);}
 if(o.key&&lit)text('✓',x+23,y-78,12);
 if(selected){text('✧',x,y-100,18);}
}
function render(){ctx.setTransform(scale,0,0,scale,0,0);if(film){RoadCinema.draw(ctx,W,H,film,RoadCharacters.draw);return;}if(scene&&sceneKey==='0:intro'&&sceneLine>=5){RoadCinema.draw(ctx,W,H,{...RoadCinema.rupture(),time:12.5},RoadCharacters.draw);return;}const isHome=mode==='home'||(!world&&mode==='modal')||ending||(sceneKey===LAST+':outro'&&sceneLine>=1)||(sceneKey==='0:intro'&&sceneLine<5);const def=isHome?LEVELS[0]:LEVELS[index];backdrop(def,isHome?0:camera,isHome);if(!isHome&&world){for(const p of world.platforms)platform(p);for(let n=0;n<world.checkpoints.length;n++){const cp=world.checkpoints[n],x=cp.x-camera;if(x>-80&&x<W+80){line(x,cp.y+58,x,cp.y+32,'#e0b98566',2);if(n<=checkpoint)glow(x,cp.y+48,32,.12);}}drawMechanisms();for(const o of world.objects)drawObject(o);if(index===2){const x=world.width-300-camera;bench(x,425,.8);character(x-20,423,'sen',1,false,true,.4);character(x+23,423,'damla',-1,false,true,.4);}if(index===5){const x=world.width-125-camera;character(x,442,'sen',-1,false,false,.6);}character(player.x-camera+13,player.y+player.h,actor,player.facing,mode==='play'&&Math.abs(player.vx)>15);if(def.mechanic==='coffee'&&state.tasks['latte-brew']&&!state.tasks['latte-serve']){for(const side of [-1,1]){const cx=player.x-camera+13+side*17,cy=player.y+player.h-23;ctx.fillStyle='#efe0c3';ctx.fillRect(cx-4,cy-8,9,11);ellipse(cx+.5,cy-8,4.5,1.5,'#bd9471');}}if(['water','lantern'].includes(def.mechanic)){const y=RoadEngine.waterLine(world,state);const g=ctx.createLinearGradient(0,y,0,600);g.addColorStop(0,'#8db7b77a');g.addColorStop(1,'#244757ee');ctx.fillStyle=g;ctx.fillRect(0,y,W,600-y);for(let n=0;n<15;n++)line((n*87+clock*15)%W,y+10+(n%5)*14,(n*87+clock*15)%W+32,y+10+(n%5)*14,'#d6e7dd33');}const f=ctx.createLinearGradient(0,490,0,600);f.addColorStop(0,'#10213300');f.addColorStop(1,'#102133ee');ctx.fillStyle=f;ctx.fillRect(0,490,W,110);}if(flash>0){ctx.fillStyle=`rgba(242,212,171,${flash*.6})`;ctx.fillRect(0,0,W,H);}const vignette=ctx.createRadialGradient(W/2,280,180,W/2,280,Math.max(W*.65,500));vignette.addColorStop(0,'#06132000');vignette.addColorStop(1,'#06132066');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);}
function frame(t){const dt=Math.min((t-last)/1000||.016,.05);last=t;if(!document.hidden){clock+=dt;flash=Math.max(0,flash-dt);advanceFilm(dt);updateChallenge(dt);if(mode==='play'){accum+=dt;while(accum>=1/120){update(1/120);accum-=1/120;}}else accum=0;render();ambience();}requestAnimationFrame(frame);}
function bindHold(id,key){const el=$(id);const pointers=new Set();el.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='play')return;pointers.add(e.pointerId);el.setPointerCapture(e.pointerId);if(key==='jump'&&!input.jump)input.jumpPressed=true;input[key]=true;el.classList.add('held');soundStart();});const release=e=>{pointers.delete(e.pointerId);if(!pointers.size){input[key]=false;el.classList.remove('held');}};el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release);el.addEventListener('lostpointercapture',release);}
bindHold('left','left');bindHold('right','right');bindHold('jump','jump');
$('filmSkip').onclick=finishFilm;$('filmPause').onclick=pause;$('endingMenu').onclick=endingMenu;$('openingReplay').onclick=()=>{$('home').hidden=true;showScene(LEVELS[0].intro,home,'0:intro');};$('musicUnlock').onclick=()=>soundStart();$('interact').onclick=interact;$('pause').onclick=pause;$('start').onclick=()=>startLevel(0);$('continue').onclick=()=>startLevel(save.current,true);$('chapters').onclick=()=>chapterMenu('home');$('about').onclick=about;$('closeModal').onclick=closeModal;$('nextLine').onclick=nextLine;$('skipScene').onclick=finishScene;$('portraitContinue').onclick=()=>{portraitAllowed=true;$('rotate').hidden=true;};$('homeSound').onclick=()=>{save.volume=save.volume>0?0:.4;soundStart();store();$('homeSound').textContent=save.volume?'♫ Ses açık':'♫ Ses kapalı';};
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const key={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump'}[e.code];if(key){e.preventDefault();if(mode==='play'){if(key==='jump'&&!input.jump)input.jumpPressed=true;input[key]=true;}}if(e.repeat)return;if(e.code==='KeyE'){e.preventDefault();interact();}if(e.code==='Enter'&&mode==='film'){e.preventDefault();return;}if(e.code==='Enter'&&mode==='scene'){e.preventDefault();nextLine();}if(e.code==='Escape'){if(mode==='modal')closeModal();else pause();}});
document.addEventListener('keyup',e=>{const key={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump'}[e.code];if(key)input[key]=false;});
window.addEventListener('blur',()=>{clearInput();suspendChallenge();if(['play','scene','film'].includes(mode))pause();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){suspendChallenge();if(music)music.stop();persist();pause();if(audioContext)audioContext.suspend().catch(()=>{});} });window.addEventListener('pagehide',()=>{persist();if(music)music.stop();});window.addEventListener('resize',resize);document.addEventListener('contextmenu',e=>e.preventDefault());
if(migrated){store();toast('Caffelab ve yeni yollar hazır. Bölümlerin ve anıların korundu.');}resize();$('continue').hidden=!Object.keys(save.states).length;$('start').hidden=Object.keys(save.states).length>0;$('homeSound').textContent=save.volume?'♫ Ses açık':'♫ Ses kapalı';requestAnimationFrame(frame);
})();
