'use strict';
const WORLDS = [
 {name:'Ankara / Koru',short:'KORU',sky:['#263f55','#b07d78','#e4ad7c'],land:'#293c41',leaf:'#475b57',accent:'#efbc75',type:'park'},
 {name:'Eskişehir',short:'ESKİŞEHİR',sky:['#182b50','#647292','#d29891'],land:'#30374e',leaf:'#465373',accent:'#efbb86',type:'city'},
 {name:'Bartın',short:'BARTIN',sky:['#152e43','#3f6a77','#8dada9'],land:'#2c484d',leaf:'#315855',accent:'#edc587',type:'rain'},
 {name:'Ankara / Tavuk Dünyası',short:'TAVUK DÜNYASI',sky:['#382d37','#896257','#c69771'],land:'#4b383b',leaf:'#735553',accent:'#f5c080',type:'cafe'},
 {name:'Koru’nun Öte Yanı',short:'KORU’NUN ÖTE YANI',sky:['#171e3c','#57567a','#aa8592'],land:'#34364b',leaf:'#494661',accent:'#ecc69a',type:'end'}
];
const LEVELS = [
 {title:'Yanımda Bir Yer',w:0,actor:'sen',mechanic:'learn',seed:2,
 goal:'Sıcak ışığı takip et. Yön tuşlarıyla yürü, ↑ ile zıpla.',
 intro:[['ANLATICI','Ankara, Koru. Dünya henüz iki kişilik.'],['DAMLA','Dostuuum… Tavuk Dünyası’na mı gitsek?'],['SEN','Senin Kremantar’ın şu an bizi beklediğini hissediyorum.'],['DAMLA','Sen de Barbeküs diyeceksin. Ama gidince yine menüye bakarsın, Aptullah.'],['SEN','Tabii bakarım. Belki bu sefer…'],['ANLATICI','Damla gülerek sana dönüyor. Vereceği cevabı duyamadan ayaklarınızın altındaki yol bir kâğıt gibi yırtılıyor.'],['SEN','Damla? Az önce buradaydın.']],
 signs:[['SEN','Bankın ışığı hâlâ sıcak. Belki bu taraftan gitmiştir.'],['SEN','Bu parkta normalde bu kadar boşluk yoktu. Belediyeye yazılacak şeyler listesi büyüyor.'],['SEN','Bir ışık daha. Tamam, dostuuum. Geliyorum.']],
 outro:[['ANLATICI','Bir anlığına karşı yolda bir gölge beliriyor. Yaklaşınca yalnızca rüzgâr kalıyor.'],['SEN','Bekle. Bir yolunu bulacağım.']],
 memory:['Bankın sağ tarafı','İkiniz de öbürünün yerini ezbere biliyorsunuz. Bazen yakınlık, sormadan biraz yana kaymak.']},
 {title:'Yolun Bittiği Yer',w:0,actor:'sen',mechanic:'crumble',seed:5,
 goal:'Çatlak zemin üzerinde oyalanma. Üç sıcak işareti bul.',
 intro:[['SEN','Yol bitti diye yolculuğun bitmesi gerekmiyor. Umarım.'],['ANLATICI','Kenarları altın rengi olan nesneler, parçalanan yolların arasında kalabiliyor. Diğerleri birer görüntü.']],
 signs:[['NOT','“Yol biterse ışığa bak. Ben de sana geliyorum. — D.”'],['SEN','Kâğıt yağmur yemiş. Ama bugün hava açıktı.'],['SEN','Altın kenarlı bir mandal. Bu notu bir yerde görmüş müydüm?']],
 outro:[['DAMLA','Dostuuum, bunu bulduğunda fazla düşünme. Işığı izle.'],['ANLATICI','Başka bir akşamın yağmuru. Aynı köşe. Henüz aynı zaman olduğunu sanıyorsun.']],
 memory:['İtiraz dilekçesi','“Buraya ‘yol bitti’ tabelası koymuşlar.” “Devamına bütçe kalmamış olabilir, Aptullah.”']},
 {title:'Aynı Bank, Başka Akşam',w:0,actor:'sen',mechanic:'wind',seed:9,
 goal:'Rüzgâr aralıklarını kullan. Banka giden ışıkları aç.',
 intro:[['SEN','Şu bank… Orada iki kişi var.'],['ANLATICI','Kız başını geriye atıp gülüyor. Yanındaki çocuk elleriyle çok ciddi bir şey anlatıyor.'],['SEN','Benim o kadar el kol hareketi yaptığım doğru değil.']],
 signs:[['SEN','O montu hatırlıyorum. Bu, bizim başka bir akşamımız.'],['ANLATICI','Görüntüye dokunamıyorsun. Anı yaşandığı hâliyle duruyor; değişen yalnızca aradaki yol.'],['SEN','Seni burada bulmuş gibi oldum. Ama sen burada değilsin.']],
 outro:[['DAMLA','Bu bank neden her seferinde ilk kez görüyormuşum gibi geliyor?'],['ANLATICI','Damla’nın tarafında ağaçların yaprakları daha yeşil.']],
 memory:['Çok ciddi bir mesele','Bir yaprağın belediyeye mi ağaca mı ait olduğunu gereğinden uzun tartışmış olabilirsiniz. Bu küçük sahne kurgu.']},
 {title:'Bir Durak Geriden',w:1,actor:'sen',mechanic:'tram',seed:12,
 goal:'Tramvay platformlarına bin. Duraklardaki ışıkları aç.',
 intro:[['ANLATICI','Eskişehir. Raylar havada, duraklar birbirinden bir akşam uzakta.'],['SEN','Bir sonraki tramvaya yetişirim. Bu kez gerçekten.']],
 signs:[['DURAKTAKİ İZ','İki bilet. Birinin tarihi silinmiş, ötekinin kenarı hâlâ yeni.'],['SEN','Aynı yola niye farklı yerlerden çıktık?'],['DAMLA’NIN İZİ','“Beklemek de bir yere gitmek sayılır mı?”']],
 outro:[['ANLATICI','Karşı kıyıda biri demir kapıya uzanıyor.'],['SEN','Hey! Kapatma, oradan geçmem gerekiyor!']],
 memory:['İki bilet','Bir şehrin ilişkinizdeki gerçek yeri, bu ilk sürümde henüz anlatılmıyor. Buradaki durak, hikâye için kurulan bir mekân.']},
 {title:'Porsuk’un Öteki Saati',w:1,actor:'sen',mechanic:'phase',seed:16,
 goal:'Saat direklerinde ✧ ile zamanı değiştir. Kesik çizgili yollar öteki akşamda katılaşır.',
 intro:[['SEN','Bu köprü az önce buradaydı.'],['ANLATICI','Saat direklerine dokununca geçmiş değişmiyor. Yalnızca yürüdüğün anı katmanı değişiyor.']],
 signs:[['SEN','Benim tarafımda pas var. Onun tarafında boya yeni.'],['ANLATICI','Bir ışık iki akşamda da yanıyor. Altın çerçeveli işaretler arada kalabiliyor.'],['SEN','Aynı yerdeyiz. Aynı anda olmayabiliriz.']],
 outro:[['DAMLA','Köprüye çıktığımda senin sesin aşağıdan gelmişti. Şimdi orada su bile yok.']],
 memory:['Suya bakmak','Su, aynı köprüyü her geçişinde başka bir görüntü taşıyor. Köprü yine de aynı köprü.']},
 {title:'Kapıyı Kapatan Adam',w:1,actor:'sen',mechanic:'gate',seed:21,
 goal:'Küçük döngü kapısını kapat; karşı yoldaki çıkış açılacak.',
 intro:[['SEN','Kapıyı kapatan kişi… Benim ceketim. Benim yürüyüşüm.'],['ANLATICI','Yüzünü tam seçemiyorsun. Ama elindeki altın halkayı tanıyorsun.']],
 signs:[['MEKANİZMA','Açık kapı: aynı yol yeniden başlar. Kapalı kapı: öteki tarafta çıkış açılır.'],['SEN','Bu küçük kapıyı kapatınca köprü kayboldu. Ama karşıdaki ışık dışarı çıktı.'],['SEN','Gelecekteki ben neden yolumu kapatsın?']],
 outro:[['ANLATICI','Siluet sana bakıyor. Dudakları kıpırdıyor: “Birini durdurmuyorum.”'],['SEN','O zaman ne yapıyorsun?']],
 memory:['Altın halka','Kapının üzerinde çizilmiş iki ok. Birisi dönüp başladığı yere geliyor. Diğeri çemberin dışına çıkıyor.']},
 {title:'Suyun Hatırladığı',w:2,actor:'sen',mechanic:'water',seed:25,
 goal:'Su yükselirken yüksek iskelelerde bekle. Üç feneri takip et.',
 intro:[['ANLATICI','Bartın. Yağmur, ahşabın üzerinde eski bir cümleyi tekrar ediyor.'],['SEN','Bu ışıkları biri benim için yakmış.']],
 signs:[['SEN','İlk fener. Önümdeki iskele aydınlandı.'],['SEN','Şu kolu biri bağlamış. Rüzgâr söndürmesin diye.'],['SEN','Üçüncüsü… Sen mi yaptın bunu?']],
 outro:[['ANLATICI','Damla’nın eli aynı fenerin camını siliyor. Ama yağmur henüz başlamamış.'],['DAMLA','Burayı karanlıkta geçemez. Önce ışıklar.']],
 memory:['Camdaki parmak izi','Kimin dokunduğunu bilmeden bir dokunuşun yardımını gördün.']},
 {title:'Sen Buradan Geç Diye',w:2,actor:'damla',mechanic:'lantern',seed:28,
 goal:'DAMLA: Üç feneri yak ve iskele geçidini hazırla.',
 intro:[['DAMLA','Pekâlâ Aptullah. Senden önce varmışım gibi görünecek.'],['ANLATICI','Şimdi Damla’yı yönetiyorsun. Biraz önce takip ettiğin ışıklar henüz yanmıyor.'],['DAMLA','Teknik olarak yön bulma işini hâlâ ben yapıyorum.']],
 signs:[['DAMLA','Bir. Camını da silelim. Hizmet kalitesi önemli.'],['DAMLA','İki. Şu kolu bağlıyorum; rüzgârda sönmesin.'],['DAMLA','Üç. Sen buradan geç diye.']],
 outro:[['ANLATICI','Senin geçtiğin iskeleye son bir tahta yerleşiyor.'],['DAMLA','Benim için ne bıraktığını henüz bilmiyorum. Ama yürüyorum.']],
 memory:['Küçük bir iş','Kurtarmak bazen büyük bir sıçrayış değildir. Bir lambanın sönmemesi için ucuna ip bağlamaktır.']},
 {title:'İlk Bulduğun, Son Bıraktığım',w:2,actor:'damla',mechanic:'note',seed:32,
 goal:'DAMLA: Son işaretleri bırak. Koru’ya ulaşan notu yaz.',
 intro:[['DAMLA','Bu parktaki köşeyi hatırlıyorum. Daha yeni ayrılmıştık.'],['ANLATICI','Sen anıların başından sonuna yürüdün. Damla sonundan başına geliyor. Aynı yollar; farklı sıra.']],
 signs:[['DAMLA','Bu ışık bir sonraki akşamda kalacak.'],['DAMLA','Bu mandal altın. Notu iki yol arasında tutabilir.'],['DAMLA','“Yol biterse ışığa bak. Ben de sana geliyorum. — D.”']],
 outro:[['ANLATICI','İlk bulduğun not, Damla’nın son bıraktığı işaretti. Yağmur lekesi şimdi oluşuyor.'],['DAMLA','Dostuuum. Umarım fazla düşünmeden ışığı izlersin.']],
 memory:['Ters okunan yol','İlk işaretin yeni bir haber değildi. Diğer yolun sonuna yakın bırakılmış bir merhabaydı.']},
 {title:'Her Zamankinden',w:3,actor:'sen',mechanic:'plates',seed:36,
 goal:'Masalarda ✧ ile tabakları değiştir: Damla’ya Kremantar, sana Barbeküs.',
 intro:[['DAMLA','Menüye bakacak mısın?'],['SEN','Bakacağım. Sonra Barbeküs söyleyeceğim. Karar sürecine saygı duy.'],['DAMLA','Ben de Kremantar’ı ilk kez seçiyormuş gibi yaparım.'],['ANLATICI','Tabaklar geliyor. Bildiğin bir akşamın sıcaklığı. Sonra masalar yolların arasında yükselmeye başlıyor.']],
 signs:[['SEN','Kremantar solda, Barbeküs sağda. Bizim masa bu.'],['SEN','Menüyü kırk sayfa da yapsalar sonuç değişmiyor.'],['ANLATICI','Sıcak ışıkta bir peçete. Üzerine çok küçük bir yıldız çizilmiş.']],
 outro:[['SEN','Burası aynı akşam. Değil mi?'],['ANLATICI','Masanın üzerindeki peçete değişiyor. Işık biraz soğuyor.']],
 memory:['Menünün amacı','“Diğer yemekler bizim ne kadar kararlı olduğumuzu görsün diye var.” “Bu açıklamayı garsona yapma, Aptullah.”']},
 {title:'İki Kişilik Masa',w:3,actor:'sen',mechanic:'compare',seed:40,
 goal:'İki akşam arasında geç. Yıldızlı peçetenin olduğu masada doğru siparişi kur.',
 intro:[['ANLATICI','Birbirine benzeyen iki ziyaret. Birinde yeşil bir hırka, diğerinde pencereye bırakılmış mavi bir atkı.'],['SEN','Aynı cümleyi mi yeniden duyuyorum?']],
 signs:[['ANLATICI','İlk akşam: yıldızlı peçete ve iki sıcak tabak.'],['ANLATICI','Diğer akşam: boş bardak, mavi atkı. Bu sahne gerçek bir ziyaret iddiası taşımayan kurgu.'],['SEN','Yemekler aynı. Aralarındaki sessizlik farklı.']],
 outro:[['DAMLA','Yine menüye ciddi ciddi bakıyorsun.'],['SEN','Barbeküs’ün fikri değişmiş olabilir.'],['ANLATICI','Yine gülüyorsunuz. Bu kez kahkahanın ardından biraz daha uzun bir sessizlik kalıyor.']],
 memory:['Yıldızlı peçete','Aynı sipariş, iki farklı gün. Benzerlik bir tekrar olduğu anlamına gelmiyor.']},
 {title:'Hesap Masada Kaldı',w:3,actor:'sen',mechanic:'cafeGate',seed:44,
 goal:'İki ziyaretin işaretlerini birleştir ve restoranın döngü kapısını kapat.',
 intro:[['SEN','İki kez geldik. Ben onları tek bir akşam sanmışım.'],['ANLATICI','Anılar bozulmadı. Yalnızca yolları birbirine karıştı.']],
 signs:[['SEN','Birinde konuşmak kolaydı.'],['SEN','Diğerinde de gülüyorduk. Bu, her şeyin aynı olduğu anlamına gelmiyordu.'],['MEKANİZMA','Kapıyı kapatmak karşı çıkışı açar. Bağlantı aynı anda kesilir.']],
 outro:[['ANLATICI','Masa yerinde kalıyor. Bir şeyi hatırlamak, o anda yaşamaya devam etmek zorunda olmak değil.'],['SEN','Hesap masada kalmış. Bazı şeyleri toplayıp kalkmayı öğrenmek gerekiyor.']],
 memory:['Sakin bir an','Bir şiiri beraber dinlediğiniz alışkanlık burada bir kitap ayracıyla hatırlanıyor. Şiir seçilmediği için alıntı yok.']},
 {title:'Bütün Yollar Buraya',w:4,actor:'sen',mechanic:'mixed',seed:49,
 goal:'Rayları, kırılgan iskeleleri ve zaman yollarını birlikte kullan.',
 intro:[['ANLATICI','Koru’nun öte yanı. Bir tramvay durağında yağmur, bir park yolunda restoran ışığı.'],['SEN','Bütün yollar buraya çıktı. Senin yolun da buradan geçiyor.']],
 signs:[['SEN','Bu feneri sen yaktın.'],['SEN','Bu notu ben çok önce buldum, sen çok sonra yazdın.'],['SEN','Geçit açık kaldıkça aynı anılara geri dönüyorsun. Artık görüyorum.']],
 outro:[['DAMLA','Çıkışın ışığını görüyorum. Her yaklaştığımda yeniden parka dönüyorum.'],['SEN','Çünkü kapı açık. Küçük mekanizmalarda olduğu gibi.']],
 memory:['Mırıldanmanın hatırası','“Şamdanları Donanınca”yı söylemeyi sevdiği hatırlanıyor. Duyduğun özgün tema o şarkının kaydı veya melodisi değil.']},
 {title:'Son Geçit',w:4,actor:'sen',mechanic:'relay',seed:53,
 goal:'İlk halkayı sen kur. Sonraki iki halkayı Damla’yla tamamla.',
 intro:[['SEN','Kapıyı kapatan kişi bendim. Henüz olmadığım ben.'],['ANLATICI','Geçit iki yolun son bağlantısı. Açık kaldıkça Damla çıkış yerine aynı anılara dönüyor.'],['SEN','Kapatırsam onun yolu açılacak. Bizim aramızdaki yol bitecek.']],
 signs:[['SEN','İlk halka hazır. Sıra sende, dostuuum.'],['DAMLA','Buradaki kol hareket etti. Demek senin tarafında biri hâlâ çalışıyor.'],['DAMLA','Son ışığı açıyorum. Bu defa dönüp aynı yere gelmek istemiyorum.']],
 outro:[['ANLATICI','İkiniz de yaşayacak ve bu dünyadan çıkabileceksiniz. Ama aynı yoldan değil.'],['SEN','Bunu bilerek yapacağım.']],
 memory:['Halkanın öte yanı','Bir mekanizma iki taraftan tamamlandı. Son adım bir düğme sürprizi değil: neyin kapanacağı artık belli.']},
 {title:'Sevgilime Bir Kefen',w:4,actor:'sen',mechanic:'final',seed:58,
 goal:'Üç halkayı tamamla. Son geçide dokunmadan önce neyin biteceğini hatırla.',
 intro:[['ANLATICI','Bu bir insana değil, birlikte hayal edilen geleceğe veda. Damla yaşıyor. Sen de buradan çıkacaksın.'],['SEN','Bir kapıyı açık tutarak bir insanı yakınımda tutamam.']],
 signs:[['SEN','Bir: Yaşadığımız şeyler olduğu gibi kalacak.'],['SEN','İki: Sen kendi yoluna devam edebileceksin.'],['SEN','Üç: Ben de çıkacağım. Yollarımız birleşmese de.']],
 outro:[['ANLATICI','Geçit kapanıyor. Damla’nın önündeki döngü çözülüyor. Işık, bir insanın kendi yoluna çıkmasına yetecek kadar açık.'],['ANLATICI','Koru. İlk akşam. Bu kez konuşma yarıda kalmıyor.'],['DAMLA','Dostuuum… Tavuk Dünyası’na mı gitsek?'],['SEN','Senin Kremantar’ın şu an bizi beklediğini hissediyorum.'],['DAMLA','Sen de Barbeküs diyeceksin. Ama gidince yine menüye bakarsın, Aptullah.'],['SEN','Tabii bakarım. Belki bu sefer…'],['DAMLA','Bu sefer de Barbeküs. Hadi kalk, dostuuum.'],['SEN','Tamam. Ama menüye bir göz atarım.'],['ANLATICI','Gülüyorsunuz. Dünya o an için iki kişilik.'],['ANLATICI','Daha sonraki bir akşam. Aynı bank. Bu kez yanında boş bir yer var. Parkın sesi devam ediyor.']],
 memory:['Kalan yer','Birlikte gülmüş olmanız, yollar ayrıldığında hiç olmamış sayılmıyor.']}
];
if(typeof module!=='undefined')module.exports={LEVELS,WORLDS};

