const path=require('node:path');
process.chdir(path.resolve(__dirname,'..'));
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const gradient={addColorStop(){}};const paint=new Proxy({}, {set(o,k,v){o[k]=v;return true;},get(o,k){if(k in o)return o[k];if(k==='createLinearGradient'||k==='createRadialGradient')return()=>gradient;return(...args)=>{for(const a of args)if(typeof a==='number')assert.ok(Number.isFinite(a),'non-finite canvas coordinate: '+String(k));};}});
class Element{constructor(){this.width=224;this.height=224;this.children=[];this.hidden=false;this.classList={add(){},remove(){},toggle(){}};this.style={};this.value='';this.checked=false;this.events={};}append(e){this.children.push(e);}addEventListener(n,f){this.events[n]=f;}setPointerCapture(){}getContext(){return paint;}setAttribute(){}removeAttribute(){}pause(){this.paused=true;}load(){}play(){this.paused=false;return Promise.resolve();}set id(v){this._id=v;nodes[v]=this;}get id(){return this._id;}set innerHTML(v){this.html=v;this.children=[];}get innerHTML(){return this.html||'';}}
const nodes={},events={},stored={};const document={getElementById:id=>nodes[id]||(nodes[id]=new Element()),createElement:()=>new Element(),querySelectorAll:()=>[],addEventListener:(n,f)=>events[n]=f,hidden:false};
const window={addEventListener:(n,f)=>events[n]=f,devicePixelRatio:1};
const context={document,window,localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>stored[k]=v},HTMLInputElement:class{},innerWidth:844,innerHeight:390,requestAnimationFrame(){},setTimeout(){return 0;},clearTimeout(){},console};
if(process.env.ROAD_LEGACY)stored['sana-gelen-yol-v1']=JSON.stringify({version:1,current:6,unlocked:8,completed:[0,1,2,3,4,5],memories:['0:memory0','0:memory1','1:memory2'],seen:[],states:{6:{checkpoint:3}},volume:.35});
vm.createContext(context);for(const f of ['progress.js','puzzles.js','logic.js','dreams.js','verses.js','reels.js','cinema.js'])vm.runInContext(fs.readFileSync(f,'utf8'),context);vm.runInContext(fs.readFileSync('story.js','utf8'),context);vm.runInContext(fs.readFileSync('levels.js','utf8'),context);vm.runInContext(fs.readFileSync('engine.js','utf8'),context);vm.runInContext(fs.readFileSync('music.js','utf8'),context);vm.runInContext(fs.readFileSync('characters.js','utf8'),context);
const code=fs.readFileSync('game.js','utf8').replace(/\}\)\(\);\s*$/,`window.test={startLevel,finishScene,interact,update,pause,closeModal,persist,respawn,home,render,showScene,complete,sceneMenu,finishFilm,advanceFilm,nextLine,selectedTrack,updateChallenge,endingMenu,get:()=>({mode,world,player,state,save,checkpoint,actor,scene,index,film,challenge}),at:(o)=>{near=o;player.x=o.x-13;player.y=o.y-58;},phase:(n)=>state.phase=n,view:(x)=>{camera=x;clock=2},line:()=>sceneLine};})();`);
vm.runInContext(code,context);const t=window.test;function timingCenter(){const ch=t.get().challenge,z=vm.runInContext('RoadPuzzles.zone('+ch.hits+','+JSON.stringify(ch.o.type)+')',context);return (Math.asin(z.center*2-1)+.85)/2.4;}
if(process.env.ROAD_LEGACY){const v=t.get().save;assert.equal(v.current,6);assert.equal(v.unlocked,8);assert.equal(v.completed.length,6);assert.equal(v.memories.length,2);assert.equal(v.states[6].checkpoint,0);t.startLevel(6,true);assert.equal(t.get().checkpoint,0);assert.equal(t.get().index,6);t.startLevel(0);for(let n=0;n<5;n++)t.nextLine();assert.equal(t.get().mode,'film');assert.equal(t.get().film.kind,'rupture');t.advanceFilm(4);t.render();const elapsed=t.get().film.time;t.pause();t.advanceFilm(3);assert.equal(t.get().film.time,elapsed);t.closeModal();t.advanceFilm(10);assert.equal(t.get().mode,'scene');assert.equal(t.line(),5);assert.ok(t.get().save.seen.includes('0:rupture'));t.finishScene();
console.log('PASS: v3 save migrates to v5, preserving chapters and unique memories with safe respawn');process.exit(0);}
for(let i=0;i<19;i++){
 t.startLevel(i);if(t.get().mode==='film')t.finishFilm();assert.equal(t.get().mode,'scene');t.finishScene();
 const s=t.get();
 for(const a of s.world.route){t.view(a.x);t.render();}
 for(const o of s.world.objects.filter(o=>o.key)){
  if(o.type==='align')t.phase(1);if(o.type==='table')t.phase(0);
  t.at(o);t.interact();
  if(o.logic){const solutions={gardenLight:[0,1,1,0],riverLight:[0,0,0,0],reunionLight:[1,1,1,1],counterweight:[1,4,2],relayWeight:[4,1,3],invitation:[0,1,2,3],tableMemory:[0,1,2,3],bookOrder:[0,1,2,3]};const q=vm.runInContext('RoadLogic.puzzles['+JSON.stringify(o.logic)+']',context),answer=solutions[o.logic];nodes.logicSubmit.onclick();assert.ok(!t.get().state.tasks[o.key],'wrong logic must not unlock');if(q.type==='order'){for(let n=0;n<answer.length;n++){const values=t.get().state.logic[o.key]||q.initial,k=Array.from(values).indexOf(answer[n]);if(k!==n){nodes['logicKey'+n].onclick();nodes['logicKey'+k].onclick();}}}else for(let n=0;n<answer.length;n++){let limit=5;while((t.get().state.logic[o.key]||q.initial)[n]!==answer[n]&&limit--)nodes['logicKey'+n].onclick();}nodes.logicSubmit.onclick();}
  if(o.type==='table'){assert.equal(t.get().mode,'modal');document.getElementById('dishLeft').onclick();document.getElementById('drinkLeft').onclick();const row=document.getElementById('modalBody').children.at(-1);row.children[0].onclick();}
  if(o.type==='coffee'){for(const id of ['coffeeDrink','coffeeMilk','coffeeCups'])document.getElementById(id).onclick();document.getElementById('modalBody').children.at(-1).children[0].onclick();}
  if(o.type==='verse'){const row=document.getElementById('verseOptions'),right=vm.runInContext('RoadVerses.questions['+o.n+'].answer',context);const correct=row.children.find(b=>b.children[1].textContent===right),wrong=row.children.find(b=>b!==correct);wrong.onclick();assert.ok(!t.get().state.tasks[o.key]);correct.onclick();assert.ok(t.get().state.tasks[o.key]);document.getElementById('verseContinue').onclick();}
  if(!o.logic&&(o.type==='brew'||o.type==='dial')){const count=o.type==='brew'?3:2;for(let n=0;n<count;n++){document.getElementById('timingStart').onclick();t.get().challenge.time=timingCenter();document.getElementById('timingStop').onclick();}}
  if(t.get().mode==='film')t.finishFilm();
  assert.equal(t.get().mode,'scene');t.finishScene();
 }
 assert.ok(s.world.objects.filter(o=>o.key).every(o=>t.get().state.tasks[o.key]));
 if(s.world.crate){const c=s.world.crate;t.get().player.x=c.x-30;t.get().player.y=c.floor-58;t.get().player.ground=c.platform;document.getElementById('right').events.pointerdown({pointerId:99,preventDefault(){}});for(let n=0;n<300;n++)t.update(1/120);document.getElementById('right').events.pointerup({pointerId:99});assert.ok(t.get().state.tasks.crate);}
 const m=s.world.objects.find(o=>o.type==='memory');t.at(m);t.interact();assert.equal(t.get().mode,'scene');t.finishScene();
 assert.ok(t.get().save.memories.includes(i+':'+m.id));
 const x=s.world.objects.find(o=>o.type==='exit');t.at(x);t.interact();
 if(i===18){assert.equal(t.get().mode,'modal');const row=document.getElementById('modalBody').children.at(-1);row.children[0].onclick();}
 assert.equal(t.get().mode,'scene');t.finishScene();assert.ok(t.get().save.completed.includes(i));if(i<18){assert.equal(t.get().mode,'film');for(const time of [0,3,6,9,10.5]){t.get().film.time=time;t.render();}t.finishFilm();if(t.get().mode==='scene')t.finishScene();}else{assert.equal(t.get().mode,'ending');assert.equal(t.selectedTrack(),'daylight');assert.equal(nodes.soundtrack.paused,false);t.endingMenu();assert.equal(nodes.soundtrack.paused,false);t.closeModal();t.pause();assert.equal(nodes.soundtrack.paused,true);t.closeModal();}
 t.startLevel(i,true);if(t.get().mode==='scene')t.finishScene();assert.ok(t.get().world.required.every(k=>t.get().state.tasks[k]));t.pause();assert.equal(t.get().mode,'modal');t.closeModal();assert.equal(t.get().mode,'play');
}
assert.equal(t.get().save.completed.length,19);assert.equal(t.get().save.unlocked,18);assert.equal(t.get().save.seen.length,58);
t.startLevel(1);t.finishScene();t.get().player.x=t.get().world.checkpoints[1].x+1;t.get().player.y=t.get().world.checkpoints[1].y;t.get().player.ground=t.get().world.checkpoints[1].platform;t.update(1/120);assert.equal(t.get().checkpoint,1);t.persist();t.startLevel(1,true);assert.equal(t.get().checkpoint,1);assert.ok(t.get().player.x>1000);
const before=t.get().player.x;t.pause();t.update(1/60);assert.equal(t.get().player.x,before);t.closeModal();document.hidden=true;events.visibilitychange();assert.equal(t.get().mode,'modal');document.hidden=false;t.closeModal();
t.respawn();assert.equal(t.get().checkpoint,1);
t.startLevel(0);t.finishScene();const initial=t.get().player.x;document.getElementById('right').events.pointerdown({pointerId:1,preventDefault(){}});t.update(.02);assert.ok(t.get().player.x>initial);document.getElementById('right').events.pointercancel({pointerId:1});const stopped=t.get().player.x;t.update(.02);assert.equal(t.get().player.x,stopped);
t.startLevel(0);t.pause();t.sceneMenu('scene');const archived=document.getElementById('modalBody').children[0];archived.onclick();t.finishScene();t.closeModal();assert.equal(t.get().mode,'scene');assert.ok(t.get().scene);t.finishScene();assert.equal(t.get().mode,'play');
t.startLevel(0);let prevented=false;const beforeLine=t.line();events.keydown({code:'Enter',target:{},preventDefault(){prevented=true;}});assert.equal(t.line(),beforeLine+1);assert.ok(prevented);t.finishScene();
// Repeated interaction cannot reopen a consumed object or duplicate a memory.
const first=t.get().world.objects.find(o=>o.key);t.at(first);t.interact();t.finishScene();t.interact();assert.equal(t.get().mode,'play');
// Timing challenges must remain recoverable after a miss or an app switch.
t.startLevel(14);t.finishScene();
const machine=t.get().world.objects.find(o=>o.type==='brew');t.at(machine);t.interact();assert.equal(t.get().mode,'play');assert.equal(t.get().challenge,null);
t.get().state.tasks['latte-order']=true;t.get().state.tasks.pressure=true;t.interact();assert.equal(t.get().mode,'modal');
nodes.timingStart.onclick();nodes.timingStop.onclick();assert.equal(t.get().challenge.hits,0);assert.ok(!t.get().state.tasks['latte-brew']);
nodes.timingStart.onclick();t.get().challenge.time=timingCenter();nodes.timingStop.onclick();assert.equal(t.get().challenge.hits,1);assert.equal(t.get().challenge.paused,true);
nodes.timingStart.onclick();t.updateChallenge(.1);const challengeTime=t.get().challenge.time;document.hidden=true;events.visibilitychange();t.updateChallenge(1);assert.equal(t.get().challenge.time,challengeTime);assert.equal(t.get().challenge.paused,true);document.hidden=false;assert.equal(nodes.timingStop.disabled,true);nodes.timingStart.onclick();t.get().challenge.time=timingCenter();nodes.timingStop.onclick();nodes.timingStart.onclick();t.get().challenge.time=timingCenter();nodes.timingStop.onclick();assert.ok(t.get().state.tasks['latte-brew']);assert.equal(t.get().mode,'scene');t.finishScene();
// A film paused in the archive resumes at the same time and returns to its next chapter.
t.startLevel(2);t.finishScene();t.complete();t.finishScene();t.advanceFilm(4);const originalFilm=t.get().film;t.pause();t.sceneMenu('film');nodes.modalBody.children[0].onclick();t.finishScene();t.closeModal();assert.equal(t.get().film,originalFilm);assert.equal(t.get().film.time,4);assert.equal(t.get().mode,'film');t.finishFilm();assert.equal(t.get().mode,'modal');
// Opening replay is available even without restarting a chapter.
t.home();nodes.openingReplay.onclick();for(let n=0;n<5;n++)t.nextLine();assert.equal(t.get().film.kind,'rupture');t.advanceFilm(4);t.pause();const filmTime=t.get().film.time;t.advanceFilm(2);assert.equal(t.get().film.time,filmTime);t.closeModal();t.advanceFilm(10);assert.equal(t.get().mode,'scene');assert.equal(t.line(),5);assert.ok(t.get().save.seen.includes('0:rupture'));t.finishScene();assert.equal(t.get().mode,'home');
// Correct verse answers survive a close/reload and unlock only their matching bridge.
t.startLevel(15);t.finishScene();const desk=t.get().world.objects.find(o=>o.type==='verse');t.at(desk);t.interact();const options=nodes.verseOptions.children;assert.equal(options.length,3);const right=vm.runInContext('RoadVerses.questions[0].answer',context);const chosen=options.find(b=>b.children[1].textContent===right);options.find(b=>b!==chosen).onclick();assert.ok(!t.get().state.tasks.verse0);chosen.onclick();t.closeModal();t.persist();t.startLevel(15,true);if(t.get().mode==='scene')t.finishScene();assert.ok(t.get().state.tasks.verse0);assert.ok(!t.get().state.tasks.verse1);assert.equal(nodes.actorLabel.textContent,'ABDULLAH');
// Attributions do not replace the speaker portrait when the protagonist is renamed.
t.startLevel(14);t.finishScene();t.complete();for(let n=0;n<8;n++)t.nextLine();assert.ok(t.get().scene.some(l=>l[0]==='ABDULLAH'&&l[1].includes('Nâtık')||l[1].includes('nâtık')));t.render();t.finishScene();

// Partially edited mechanisms survive closing/reloading without opening their gate.
t.startLevel(9);t.finishScene();const mirror=t.get().world.objects.find(o=>o.logic==='gardenLight');t.at(mirror);t.interact();nodes.logicKey0.onclick();const partial=JSON.stringify(t.get().state.logic[mirror.key]);t.closeModal();t.persist();t.startLevel(9,true);if(t.get().mode==='scene')t.finishScene();assert.equal(JSON.stringify(t.get().state.logic[mirror.key]),partial);assert.ok(!t.get().state.tasks[mirror.key]);
// New introduction and collapse can be skipped, paused and resumed without dropping story callbacks.
t.startLevel(10);assert.equal(t.get().film.kind,'dream-reunion');t.advanceFilm(5);t.pause();t.advanceFilm(2);assert.equal(t.get().film.time,5);t.closeModal();t.finishFilm();assert.equal(t.get().mode,'scene');t.finishScene();t.complete();t.finishScene();assert.equal(t.get().film.kind,'dream-collapse');t.advanceFilm(16);t.render();t.finishFilm();assert.equal(t.get().mode,'scene');assert.ok(t.get().scene.some(l=>l[1].includes('hayaldi')));t.render();t.finishScene();assert.equal(t.get().mode,'modal');
console.log('PASS: 19 chapters, animated rupture, skippable interludes, final music, distinct chapter tasks and physical crate puzzles, table puzzle, final confirmation, 58 chapter/film replay entries, progress and checkpoint reload, pause, visibility and respawn');
