const assert=require('node:assert/strict'),{LEVELS}=require('../story.js'),P=require('../progress.js'),Q=require('../puzzles.js'),E=require('../engine.js');
for(const [old,final,relay]of [[4,14,13],[5,15,14],[6,16,15]]){
 const raw={version:1,layoutVersion:old,current:final,unlocked:final,completed:[0,8,final],memories:[final+':memory'],seen:[final+':outro'],states:{[final]:{checkpoint:3,tasks:{seal1:true,seal2:true},actor:'sen',phase:1},[relay]:{checkpoint:2,tasks:{relay0:true},actor:'damla'}},volume:.25};
 const {save:v,migrated}=P.migrate(raw,LEVELS);assert.ok(migrated);assert.equal(v.current,18);assert.equal(v.unlocked,18);assert.deepEqual(v.completed,[0,8,18]);assert.deepEqual(v.memories,['18:memory']);assert.deepEqual(v.seen,['18:outro']);assert.equal(v.states[18].checkpoint,3);assert.equal(v.states[18].tasks.seal1,true);assert.equal(v.states[17].actor,'damla');assert.equal(v.volume,.25);assert.equal(v.states[9],undefined);assert.equal(v.states[10],undefined);assert.deepEqual(P.migrate(v,LEVELS).save,v);assert.equal(P.migrate(v,LEVELS).migrated,false);
}
const v6=P.migrate({version:1,layoutVersion:6,current:9,unlocked:12,completed:[0,8,9,10],memories:['12:memory'],seen:['12:outro','13:film'],states:{9:{checkpoint:3,tasks:{order:true}},12:{checkpoint:5,tasks:{pressure:true}}}},LEVELS).save;assert.equal(v6.current,11);assert.equal(v6.unlocked,14);assert.equal(v6.states[11].tasks.order,true);assert.equal(v6.states[14].checkpoint,5);assert.deepEqual(v6.memories,['14:memory']);assert.deepEqual(v6.seen,['14:outro','15:film']);
const ancient=P.migrate({version:1,current:14,unlocked:14,completed:[],memories:['14:memory0','14:memory1'],states:{14:{checkpoint:9}}},LEVELS).save;assert.equal(ancient.states[18].checkpoint,0);assert.deepEqual(ancient.memories,['18:memory']);assert.equal(P.fresh().layoutVersion,7);
assert.ok(Q.coffeeOK({drink:1,milk:1,cups:2}));assert.ok(!Q.coffeeOK({drink:1,milk:0,cups:2}));assert.ok(Q.tableOK([1,0],[1,0],0,true));assert.ok(!Q.tableOK([1,0],[1,0],1,true));
for(const type of ['brew','dial'])for(let hit=0;hit<(type==='brew'?3:2);hit++){const z=Q.zone(hit,type),t=(Math.asin(z.center*2-1)+.85)/2.4;assert.ok(Q.inWindow(t,hit,type));assert.ok(!Q.inWindow((Math.asin((z.center+.16)*2-1)+.85)/2.4,hit,type));assert.ok(z.width<.13);}
const w=E.makeLevel(2,LEVELS[2]);let peak=0;for(let n=0;n<1500;n++)peak=Math.max(peak,Math.abs(E.wind(w,{time:n/100,assist:false})));assert.ok(peak>50&&peak<=61);
console.log('PASS: v4/v5/v6→v7 numbering, checkpoint/actor/tasks/audio preserved; new chapters not fabricated complete; changing timing windows');
