const assert=require('node:assert/strict'),{LEVELS}=require('../story.js'),P=require('../progress.js'),Q=require('../puzzles.js'),E=require('../engine.js');
const old={version:1,layoutVersion:4,current:14,unlocked:14,completed:[0,11,12,13],memories:['12:memory','14:memory'],seen:['0:intro','12:outro','13:intro','14:outro'],states:{14:{checkpoint:3,tasks:{seal0:true,seal1:true},actor:'sen',phase:1},13:{checkpoint:2,tasks:{relay0:true},actor:'damla'}},volume:.25};
const {save:v,migrated}=P.migrate(old,LEVELS);assert.ok(migrated);assert.equal(v.current,16);assert.equal(v.unlocked,16);assert.deepEqual(v.completed,[0,11,14,15]);assert.deepEqual(v.memories,['14:memory','16:memory']);assert.deepEqual(v.seen,['0:intro','14:outro','15:intro','16:outro']);assert.equal(v.states[16].checkpoint,3);assert.equal(v.states[16].tasks.seal0,true);assert.equal(v.states[15].actor,'damla');assert.equal(v.volume,.25);assert.equal(v.states[12],undefined);
assert.deepEqual(P.migrate(v,LEVELS).save,v,'migration is idempotent');assert.equal(P.migrate(v,LEVELS).migrated,false);
const ancient=P.migrate({...old,layoutVersion:1,memories:['14:memory0','14:memory1']},LEVELS).save;assert.deepEqual(ancient.memories,['16:memory']);assert.equal(ancient.states[16].checkpoint,0);assert.equal(P.migrate(null,LEVELS).save.layoutVersion,6);
assert.equal(Q.coffeeOK({drink:1,milk:1,cups:2}),true);for(const bad of [{drink:0,milk:1,cups:2},{drink:1,milk:0,cups:2},{drink:1,milk:1,cups:1}])assert.equal(Q.coffeeOK(bad),false);
assert.ok(Q.tableOK([1,0],[1,0],0,true));assert.ok(!Q.tableOK([1,0],[0,0],0,true));assert.ok(!Q.tableOK([1,0],[1,0],1,true));
assert.ok(Q.inWindow(.85/2.4));assert.ok(!Q.inWindow(1));
const w=E.makeLevel(2,LEVELS[2]);let peak=0;for(let n=0;n<1500;n++)peak=Math.max(peak,Math.abs(E.wind(w,{time:n/100,assist:false})));assert.ok(peak>50&&peak<=61);assert.ok(Math.abs(E.wind(w,{time:1,assist:true}))<Math.abs(E.wind(w,{time:1,assist:false})));
console.log('PASS: legacy save numbering/checkpoints/actor/audio preserved; coffee, shared ayran, timing window, and stronger wind');

const v5=P.migrate({version:1,layoutVersion:5,current:15,unlocked:15,completed:[12,13,14,15],seen:['12:outro','13:film','15:outro'],memories:['12:memory','15:memory'],states:{12:{checkpoint:5,tasks:{pressure:true}},15:{checkpoint:3,tasks:{seal2:true}}}},LEVELS).save;assert.equal(v5.current,16);assert.deepEqual(v5.completed,[12,14,15,16]);assert.equal(v5.states[12].checkpoint,5);assert.equal(v5.states[13],undefined);assert.equal(v5.states[16].tasks.seal2,true);assert.deepEqual(P.migrate(v5,LEVELS).save,v5);
